### ISSUE TITLE
[14.0]Language switcher does not work

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#100]
The language code displayed on the webpage, where the "_" is not changed to a "-"
![无标题](https://user-images.githubusercontent.com/11767049/102301474-cd2cb880-3f91-11eb-83cd-a93ef7aaa2a0.jpg)

**Comment by niulinlnc** [comment]
https://github.com/niulinlnc/odoo-formio/commit/802f906914d320b5d8c9a878c59316c841ea8f55

**Comment by bobslee** [comment]
@niulinlnc I found the issue (a left piece of code)
https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/views/formio_public_templates.xml#L60

I shall change.

**Comment by bobslee** [comment]
@niulinlnc I just discoved you already changed this in PR https://github.com/novacode-nl/odoo-formio/pull/99
Please keep PR's as sensible as possible :)

**Comment by bobslee** [comment]
Thanks! I just pushed c0692a14bae17179d527f361a201132fc934cd31 into 14.0, 13.0, 12.0
