### ISSUE TITLE
[14.0]The public form builder cannot display the expected language

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#101]
The following operations, I expected to display Chinese, but the builder displays English:
1.English Enabled Uncheck.
2. The builder adds Chinese entries.
3. Open the public builder and fill in the form, which is displayed in English.

**Comment by bobslee** [comment]
@niulinlnc I expect you mean the public **Form** and not **Form Builder**?
Form Builders are in backend, behind login ;)

Do you have a solution/fix for this?
Otherwise I'll try to reproduce, discuss or fix .. maybe upcoming days.

**Comment by bobslee** [comment]
@niulinlnc should be fixed now. 

I tested **language buttons** and **translations** thoroughly on **website page** with combinations of:
- Odoo website language switcher
- Forms language switcher: no buttons if 1 language, multiple language buttons etc.
- Form Builder setting/field `English Enabled`: unchecked and checked.
 
Please review and keep me posted :)

**Comment by niulinlnc** [comment]
Resolved, closed issue.
