### ISSUE TITLE
[<= 13.0] formio: WARNING The transient model formio.version.github.checker.wizard should not have explicit access rules!

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-formio#104]
Upon install or upgrade of the `formio` module following 2 warnings occur.
These don't occur on version 14.0.

No obviuous change/solution yet.

```
WARNING [DB] odoo.modules.loading: The transient model formio.version.github.tag.available (Formio Version GitHub Tag Available) should not have explicit access rules! 
WARNING [DB] odoo.modules.loading: The transient model formio.version.github.checker.wizard (Formio Version GitHub Checker Wizard) should not have explicit access rules!
```

**Comment by bobslee** [comment]
No waning since Odoo 14.
It's not obvious how to solve/workaround in version <= 13. 

The load_modules (function) has been changed 14 and warning had been removed. 

- 13: https://GitHub.com/odoo/odoo/blob/13.0/odoo/modules/loading.py#L462
- 14: https://github.com/odoo/odoo/blob/14.0/odoo/modules/loading.py#L356 (no more warning)

**Comment by Lefetch** [comment]
did you solve it in v13 ?

**Comment by bobslee** [comment]
I'm unsure, don't think so.
See my comment above `It's not obvious how to solve/workaround in version <= 13.`

So you can just test and review.
