### ISSUE TITLE
formio Storage URL Provider: e.g. to store a file (component) upload as Odoo attachment (in filestore)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-formio#105]
Currently the File component can only be stored as Base64 (storage provider), in the Form its submission data (database record).

Disadvantages e.g. especially with large (RAW) images:
- Database size quickly increases
- Database Base64 writing record lock, performance etc.

Implement the File component URL Storage Provider.

**Comment by walkerblackwell** [comment]
often the max-upload size spec for odoo is something tiny like 20MB (for odoo.sh it is). Do you think there would be a way to hook this to google drive via API? Or possible use node/java server (a requirement to run odoo anyway) to upload to files directory? Or a way to get around this by chunking in python?

best regards
Walker

**Comment by bobslee** [comment]
Yep @walkerblackwell,that (all) would be possible.

In a matter of fact...
I'm now prepping a new module release `formio_storage_filestore`
Which enables us to upload files into Odoo's filestore (linked with attachments on Form).

Regarding file storage APIs:
It would be possible to develop other storage providers e.g. Google Drive, Dropbox.. with the implementation ideas (HTTP/URL endpoints) of the new module.

I'm willingly to share and collaborate :)

**Comment by bobslee** [comment]
@walkerblackwell just released for version 14 and 13.
https://apps.odoo.com/apps/modules/14.0/formio_storage_filestore/

Prepping a release for version 12.

**Comment by walkerblackwell** [comment]
> @walkerblackwell just released for version 14 and 13.
> https://apps.odoo.com/apps/modules/14.0/formio_storage_filestore/
> 
> Prepping a release for version 12.

Downloaded/installed in v13 for testing. Works great! It uploads more than 25MB on odoo.sh too!

I don't see the attachment in chatter though. And looking at the json data I see the file url but this does not download, just goes to blank front-end (theme) page. Maybe this is some setting I have wrong in the form . . . I'll check.

cheers on all the hard work!
-Walker

**Comment by bobslee** [comment]
@walkerblackwell To solve the issue with the attachments...
Please update the PyPi `formio-data`. It has necessary changes for the `fileComponent` class.

`pip3 install -U formio-data`

**Comment by bobslee** [comment]
@walkerblackwell Regarding the Google Drive storage.

This requires an additional module similar to `formio_storage_filestore`.

IMHO the module should implement the URL (POST, GET) endpoints for `/formio/storage/googledrive`
Similar implementation as the filestore module ;)

So Google Drive interface/service is only implemented serverside.

**Comment by bobslee** [comment]
Hey @walkerblackwell, I close this. Has been implemented and released now.
Keep me posted if you've other questions or ideas :)
