### ISSUE TITLE
Create Partner/Contact and add to Followers Not Working?

### ISSUE THREAD

**Issue by walkerblackwell** [novacode-nl/odoo-formio#107]
I am attempting to add a contact (from form data) to the form upon submission so I can create a report and email this to the customer from their public form submission (as confirmation). This seems rather straightforward. I created a test email/name field set, added these in Components / API and check "add to followers". Then I make sure it's published as public. 

Example form builder: https://demo13.novacode.nl/web#id=159&action=149&model=formio.builder&view_type=form&cids=1&menu_id=124

The problem is there is no partner/contact linked or created or added to followers on the form submission. Am I missing something? the form builder also has res.partner resource linked but having this linked or unlinked changes nothing.

best regards,
Walker

**Comment by bobslee** [comment]
Hi @walkerblackwell,
I understand and should work :)

Please change the **fields/names in tab "Components API"** (screenshot left) to match the **Property Names in tab "API"** (screenshot right).

So in this example just lowercase.

![image](https://user-images.githubusercontent.com/328803/104426528-58de3880-5582-11eb-9d12-debedea0ef30.png)

**Comment by walkerblackwell** [comment]
It works!

The problem I found came from trying to add my own name/email which is the contact info of an internal user and this was causing a singleton error in the logs and not submitting the form (aka, not running the automation to add the follower). Submitting the form with a non-internal contact email works.

best regards,
Walker

**Comment by bobslee** [comment]
@walkerblackwell Thanks for reporting the situation. 

Does this imply a bug or need for improvement?
I would like to reproduce and improve anyway. 

Which Odoo version you use, 13 ?

**Comment by walkerblackwell** [comment]
v13,

I would say it's a bug as I could see many scenarios where internal users are filling out public facing forms and needing confirmation emails.

regards,
Walker

**Comment by bobslee** [comment]
Ok affirmative. 
Shall we reopen this issue or could you submit a new issue please?
