### ISSUE TITLE
Add the custom CSS asset to the published form to allow for customized CSS on form snippets :enhancement

### ISSUE THREAD

**Issue by walkerblackwell** [novacode-nl/odoo-formio#108]
Currently embedded forms use formio_form_embed.css. It would be nice to place custom css assets below this to allow for customized embeds (aka, to d-none the form title, set background color, etc).

cheers!
Walker

**Comment by bobslee** [comment]
Hi @walkerblackwell 
Just hooking in this suggestion.
Soon I'll release a theming module, which provides styling (CSS, assets) per form builder.
It will be available in the Odoo Apps Store.
Hereby I close this issue.
