### ISSUE TITLE
[V12] Unable to populate a select field with odoo data

### ISSUE THREAD

**Issue by ygol** [novacode-nl/odoo-formio#11]
I am trying to create a simple form containing a select field that is populated with odoo data.

1. created a form builder & added resource model (formio_res_model_id) = "Sale Order".
2. the notebook tab "Resource Settings" is unhided but empty.
3. click on "Form Builder".
4. add a "Select" component and under Data choose  Data Source Type = "Resource"

- Shouldn't I get  somethin to select under "Resource" (in the same Data tab)?

- I do not have the buttons "Settings in Odoo" and "Odoo" at the top of the builder's view as shown in: https://apps.odoo.com/apps/modules/12.0/formio/intro-screenshot-1.png

Am I missing something?

Thanks in advance.

**Comment by bobslee** [comment]
Hi,
No.. a Formio Resource isn't integrated with Odoo.
Did you installed the `formio_sale` module as well?

Which version of the module do you use?
Did you tried on the Demo environment?

**Comment by ygol** [comment]
> Hi,
> No.. a Formio Resource isn't integrated with Odoo.
> Did you installed the `formio_sale` module as well?
> 
> Which version of the module do you use?
> Did you tried on the Demo environment?

I tried  on the Demo too. and also have installed "formio_sale". 

So how would I demo: ?

> "Provide Form-fields with data from Odoo. For example: a selection/dropdown field where choices are Odoo Products, filtered by some product-category." 

tnx again

**Comment by bobslee** [comment]
This (for I know currently) only works with **Select component**.

For example - the following  shows (product) names from Sale order lines.
So resource model: `sale.order`

![image](https://user-images.githubusercontent.com/328803/74562162-7e298780-4f6a-11ea-942a-5b7f113a4ef0.png)

Also see the URL endpoint (Odoo Formio controller) which implements this. See the comment and options to use in URL query-params.
https://github.com/novacode-nl/odoo-formio/blob/12.0/formio/controllers/main.py#L321

**Comment by ygol** [comment]
Yes, I tried that but it doesn't seem to work for me. 

On your runbot:
- to what version of the builder does your snapshot correspond? I could not find the same one. I tried latest and 4.7.8.
- I tried both examples from your code (access to data unrelated to res_data at L278 and your example at L326) 
- I succeeded to get something with the following direct URL:
> https://odoo12-b4a887d572e9.victhorious.com/formio/form/data/1961b599-a67c-4164-a0f8-814fdcf8e92a?model=res.partner&label=name&domain_fields=function&city=Sittard

I get:

> [{"id": 14, "label": "Azure Interior"}, {"id": 26, "label": "Brandon Freeman"}, {"id": 33, "label": "Colleen Diaz"}, {"id": 27, "label": "Nicole Ford"}, {"id": 10, "label": "Deco Addict"}, {"id": 35, "label": "Addison Olson"}, {"id": 18, "label": "Douglas Fletcher"}, {"id": 19, "label": "Floyd Steward"}, {"id": 11, "label": "Gemini Furniture"}, {"id": 20, "label": "Edwin Hansen"}, {"id": 22, "label": "Jesse Brown"}, {"id": 31, "label": "Oscar Morgan"}, {"id": 23, "label": "Soham Palmer"}, {"id": 15, "label": "Lumber Inc"}, {"id": 34, "label": "Lorraine Douglas"}, {"id": 12, "label": "Ready Mat"}, {"id": 21, "label": "Billy Fox"}, {"id": 25, "label": "Edith Sanchez"}, {"id": 37, "label": "Julie Richards"}, {"id": 24, "label": "Kim Snyder"}, {"id": 36, "label": "Sandra Neal"}, {"id": 30, "label": "Theodore Gardner"}, {"id": 38, "label": "Travis Mendoza"}, {"id": 13, "label": "The Jackson Group"}, {"id": 29, "label": "Gordon Owens"}, {"id": 28, "label": "Toni Rhodes"}, {"id": 9, "label": "Wood Corner"}, {"id": 17, "label": "Ron Gibson"}, {"id": 32, "label": "Tom Ruiz"}, {"id": 16, "label": "Willie Burke"}, {"id": 1, "label": "YourCompany"}, {"id": 39, "label": "Chester Reed"}, {"id": 40, "label": "Dwayne Newman"}, {"id": 8, "label": "Joel Willis"}, {"id": 7, "label": "Marc Demo"}, {"id": 3, "label": "Mitchell Admin"}, {"id": 41, "label": "celery"}]

But as you can see, the "filtering part" ("&domain_fields=function&city=Sittard") doesn't work.  But I am unable to get the same result into a list element in the form.

- I can't get anything useful in the logs (on my server).

**Comment by bobslee** [comment]
Ok thanks for checking and the log.
I shall take a look (and fix) upcoming days.
Shall let you know.

**Comment by lieblinger** [comment]
Can confirm when I'm passing the url directly with following schema it works.

https://server_adress/formio/form/data/<uuid from db>?model=res.partner&label=name

It looks like the form is not transmitting the uuid to the controller and that's why the function is not displaying the desired content.

Wouldn't it a work around to remove the if not form check?

**Comment by bobslee** [comment]
Hi @ygol, @lieblinger 
I just pushed some changes to v11 and v12 branches, to address this issue.
Please could you test and report here?

Required steps:
- Download and replace with latest version of modules: `formio` and `formio_sale`
- Install or upgrade `formio_sale`
- Test with the new `formio_sale` Form Builder record **Demo Sale 1**

v12:
https://github.com/novacode-nl/odoo-formio/blob/12.0/formio_sale/data/formio_demo_data.xml

v11:
https://github.com/novacode-nl/odoo-formio/blob/11.0/formio_sale/data/formio_demo_data.xml

**Comment by bobslee** [comment]
By the way, mind the URL in the Select component its `Data Source URL` field.
From now on it's **without** a leading "/".

So the correct `Date Source URL` are just:
- `data` (to query all Odoo models)
- `res_data` (to query from related/resource Odoo model)

**Comment by bobslee** [comment]
You could check my v12 demo. It's already deployed over there.
https://odoo12-b4a887d572e9.victhorious.com/

There's a "Demo Sale 1" form builder, with 2 Select components fetching data from Odoo.
https://odoo12-b4a887d572e9.victhorious.com/web#id=97&action=114&model=formio.builder&view_type=form&menu_id=83

**Comment by lieblinger** [comment]
Checked your updated online instance and tried it also on my local odoo and flectra enviroment, but it's stilll not working. 

I've putted a print statement into the form_data controller function. The print() command is never excuted, so it seems like there's still something wrong.

By the way... Before your last commit it only worked with **fqdn +  /formio/form/data/ + manual uuid** in the formio url field. When I putted only /formio/form/data without fqdn in the url field it didn't work.

**Comment by bobslee** [comment]
Did you merged all my latest changes into your Flectra fork?

**Comment by lieblinger** [comment]
Tested your online demo (link below) right now in edge and chrome with cleared browser cache and it's not working. See screenshot.

https://odoo12-b4a887d572e9.victhorious.com/web#id=97&action=114&model=formio.builder&view_type=form&menu_id=83
![formio](https://user-images.githubusercontent.com/10740088/76120695-528e4000-5ff2-11ea-81c6-eeebde8e7761.jpg)

**Comment by bobslee** [comment]
That makes sense. Such events don't work (yet) from the Form Builder.
Please create a Form and try again :)

I just tested with the Form: https://odoo12-b4a887d572e9.victhorious.com/web?#id=96&view_type=form&model=formio.form&action=116&menu_id=83

The JSON-RPC request from the Form Builder needs to be blocked somehow.

**Comment by lieblinger** [comment]
That really makes sense 👍  

In a Form it works great on flectra and odoo v11.

**Comment by bobslee** [comment]
Thanks for reviewing @lieblinger. I really appreciate it!
BTW you can also enable the "Multiple values" option for a Select component.

**Comment by bobslee** [comment]
Closed this issue. No further info received.

**Comment by bobslee** [comment]
Prefix URLs with a "/", indicating it's relative. So from now on:
- `/data`
- `/res_data`

**Comment by framatt** [comment]
Does someone have a working example on how to set this up?

**Comment by bobslee** [comment]
@framatt see this issue with my examples.
You only need to change the **Data Source URLs**... like a mentoined in my previous comment.

If you need more support, send me a DM mail: `bob (at) novacode (dot) nl`
