### ISSUE TITLE
formio_report_qweb Edit Grid + nested layout elements inside data elements (aka, Columns, etc) :enhancement

### ISSUE THREAD

**Issue by walkerblackwell** [novacode-nl/odoo-formio#112]
Currently the qweb report will default to raw json if a column element is inside of a data element. Column layout elements are important inside of data or edit grid components because they allow for specific design of forms during "add another" scenarios, aka food ordering, etc.

Also edit grids are not supported (very similar to data grids I think).

regards,
Walker

**Comment by bobslee** [comment]
FYI @walkerblackwell 
I'm now implementing this improvement. Which requires some improvements in my Python formiodata (PyPi) library.
Quite an effort, but datagrid with nested layout components (eg column, panel) works now.
Keep you posted!

**Comment by bobslee** [comment]
@walkerblackwell I just pushed a change (release) for this feature in the `formio_report_qweb` module: https://github.com/novacode-nl/odoo-formio/commit/a7a6e66a03554b807b909411ba414d7d7d3c47dc
Already deployed on my Odoo demo: https://demo13.novacode.nl/

Actually the most effort lies in (my) Python formio-data API library: https://github.com/novacode-nl/python-formio-data
Still need to implement **edit grid** (maybe other components) at request or by PRs.

Can't wait for your review, suggestions or even PR :-)

**Comment by walkerblackwell** [comment]
I will test when I have the time.

thank you thank you

**Comment by bobslee** [comment]
Hi @walkerblackwell, I'm glad to announce...

During yesterday's development sprint, we solved to transform complex nested Form structures (eg inside layouts, grids) into usable Python programming objects.

Extensive unittest passes now and I tested several complex nested Forms in Odoo QWeb printing. 

From now on the the PDF (QWeb) reports and Forms Data API can handle (almost) any complex Forms we'll be using.

Would be great if you could test and update this issue please.

You'll need to update:
- pip3 install -U formio-data
- Odoo `formio_ report_qWeb` module

Datagrid shall be handled, but still to implement the Editgrid.

**Comment by bobslee** [comment]
@walkerblackwell I close this issue now.
We've accomplished this feature for nested layout components and datagrid. 
Still on the roadmap is to implement the editgrid component. I expect this when a need or funding arises.
