### ISSUE TITLE
How to populate the odoo data in select filed via odoo 13?

### ISSUE THREAD

**Issue by elliotxin** [novacode-nl/odoo-formio#116]
In Odoo 13, I create one form, and in the Res Model, I choose sale.order, I want to create one select field, the user can use this select field to select the Odoo customer name, which like the "res. partner " name to show in the select field. Anyone can guide me on how to do this? Thanks a lot.

**Comment by bobslee** [comment]
Copy the JSON below into the `Edit JSON` (wrench icon) of a **Select field/component**.
![image](https://user-images.githubusercontent.com/328803/106254905-8b8e5f00-6219-11eb-978c-a4f52bc186c9.png)

This fetches all `res.partner` records and shows its `name` field value.
How this basically works can be studied (see comments or code): 
- https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/controllers/main.py#L177
- How to configure this in the Formio Select component: https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/controllers/main.py#L184

Currently only authenticated users can use this data URL.

```
{
  "label": "Customer",
  "widget": "choicesjs",
  "tableView": true,
  "dataSrc": "url",
  "data": {
    "url": "/data",
    "headers": [
      {
        "key": "",
        "value": ""
      }
    ],
    "values": [],
    "json": "",
    "resource": "",
    "custom": ""
  },
  "selectThreshold": 0.3,
  "key": "customer",
  "type": "select",
  "indexeddb": {
    "filter": {}
  },
  "filter": "model=res.partner&label=name",
  "input": true,
  "disableLimit": false,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "defaultValue": null,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "calculateServer": false,
  "attributes": {},
  "validateOn": "change",
  "validate": {
    "required": false,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false
  },
  "conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
  "overlay": {
    "style": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "clearOnRefresh": false,
  "limit": 100,
  "valueProperty": "",
  "lazyLoad": true,
  "searchEnabled": true,
  "searchField": "",
  "minSearch": 0,
  "readOnlyValue": false,
  "authenticate": false,
  "template": "<span>{{ item.label }}</span>",
  "selectFields": "",
  "searchThreshold": 0.3,
  "uniqueOptions": false,
  "fuseOptions": {
    "include": "score",
    "threshold": 0.3
  },
  "customOptions": {},
  "id": "ewcr0yf"
}
```

**Comment by bobslee** [comment]
@elliotxin Could you confirm whether this is solved?

**Comment by elliotxin** [comment]
I followed your instruction, unfortunately, its seems not working.
![image](https://user-images.githubusercontent.com/3390411/106567219-6fb5f080-656c-11eb-835a-d73e5bd4384c.png)
![image](https://user-images.githubusercontent.com/3390411/106567269-89573800-656c-11eb-9003-afeaf29b69fd.png)

**Comment by bobslee** [comment]
@elliotxin thanks for sharing!

Following questions and remarks. Please answer so we can analyse and have a clear case.

1. Could you share theresponse of the `/data` request(s) ? 

2. Any error visible in the odoo log?

3. The `/data` and `/res_data` requests only allow authenticated users.
In case you're using in website (public user) this won't work (yet).

4. The `Res(ource) Model` fields (also `res_id`) ain't involved in the `/data` request.
Those `Res(ource) Model` fields can be used in the `/res_data` request, implemented in https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/controllers/main.py#L227

**Comment by elliotxin** [comment]
@bobslee 
Actually, it's working in the backend, but won't work on the website, in my requirement, I want it to work on the website.

**Comment by bobslee** [comment]
@elliotxin Ok, glad you experienced it works in backend.

To implement (access) this on the website, it involves some security considerations and good practice.
I don't want to open/grant requests to every model in Odoo.

Do you've a suggestion? Feel free to describe and maybe submit a PR?
Otherwise you could send me a DM (mail), so we can agree on broader support and efforts from my end.

**Comment by bobslee** [comment]
@elliotxin I assume you don't want to elaborate further on this anymore?

**Comment by bobslee** [comment]
Please re-open and comment if the request remains.

**Comment by bobslee** [comment]
@elliotxin Populating a select component (now) works for a Form on the website.
Just setup model access (fine grain with record rules) for the public user group.
