### ISSUE TITLE
Export Attachment

### ISSUE THREAD

**Issue by framatt** [novacode-nl/odoo-formio#117]
When creating a PDF in Odoo, can the attachments be converted to pdf?

**Comment by bobslee** [comment]
@framatt which attachments do you mean?
Maybe add screenshot to explain.

Also specify your versions:
- Odoo
- `formio`
- `formio_report_qweb`

**Comment by framatt** [comment]
This is for Odoo 12.
These attachments
![image](https://user-images.githubusercontent.com/61408825/106445906-46239900-6488-11eb-9945-33a42b1ed52f.png)

is it possible to export them in pdf when printing the form with the process shown below

![image](https://user-images.githubusercontent.com/61408825/106446028-6eab9300-6488-11eb-8f1d-3dcb28e7e304.png)

**Comment by bobslee** [comment]
Yes, it's possible to print the File (component) uploads in a PDF.

Please first try following:
1. Upgrade the `formio-data` PyPi package... `pip3 install -U formio-date`
2. Form Builder: File component checkbox "Display as Image" (see screenshot)
![image](https://user-images.githubusercontent.com/328803/106448562-39507680-6483-11eb-975a-db0fc61397d7.png)

**Comment by bobslee** [comment]
@framatt Any new info in this regard?
