### ISSUE TITLE
Submission User and Submission Partner Data in Odoo 12

### ISSUE THREAD

**Issue by framatt** [novacode-nl/odoo-formio#118]
How is Submission User and Submission Partner Data in Odoo 12 calculated? Can it be changed?

**Comment by bobslee** [comment]
Please provide more info.
Which additional module(s) this occurs and provide some steps, maybe screenshots.

**Comment by framatt** [comment]
![image](https://user-images.githubusercontent.com/61408825/106445651-f80e9580-6487-11eb-9a81-6b790e066d12.png)

How are these values determined? Its a Public Form on the website

**Comment by bobslee** [comment]
@framatt  please answer questions in screenshot.

![image](https://user-images.githubusercontent.com/328803/106447448-c98dbc00-6481-11eb-92a7-b555b608fa0b.png)

**Comment by framatt** [comment]
"While submitting the form, who was logged-in??"

No One. Somehow its associating that user with the webuser??Website user?? But like I said, its a public form

**Comment by bobslee** [comment]
See screenshot, in a clean Odoo v.13 database with modules: formio, form_crm, website_formio.
No issue here.

To test with v.12, one needs to put the Form `<iframe/>` on the webpage manually, right?
Becasue the website snippet isn't available.
![image](https://user-images.githubusercontent.com/328803/106449278-18d4ec00-6484-11eb-9a74-d0e8ca02a32c.png)

**Comment by bobslee** [comment]
Could you test on my demo environment, with identical setup and data ?

https://demo13.novacode.nl/

Login:
- user: demo
- pass: demo

**Comment by framatt** [comment]
Sure, I will test soon and revert back to you

**Comment by bobslee** [comment]
Hi @framatt , could you let us know whether it's solved for you?

**Comment by bobslee** [comment]
@framatt Any new info in this regard?
