### ISSUE TITLE
Issue During The MegaMenu Creation 

### ISSUE THREAD

**Issue by dustundag** [novacode-nl/odoo-formio#119]
Hi I get the follwing error and not able to add Megamenu.You are not allowed to access 'website.editor.unsanitize.html.field' (website.editor.unsanitize.html.field) records. Şu anda hiçbir grup bu işleme izin vermiyor. Contact your administrator to request access if necessary.Droggol, 21:41Hello,

As per the error message that you've given me. there is an issue with the model 'website.editor.unsanitize.html.field'. and I think it is from any custom module. because we didn't add such a model to our theme.

I just found one module that has exactly the same model name in it.
Did you install this module on your server? https://apps.odoo.com/apps/modules/14.0/website_editor_unsanitize_html_field/

**Comment by bobslee** [comment]
Hi @dustundag, I analysed and spotted the bug. Thanks for the issue report!
Shall fix now and let you know.

**Comment by bobslee** [comment]
Please download and replace this module: https://apps.odoo.com/apps/modules/14.0/website_editor_unsanitize_html_field/
Let me know whether has been fixed.

**Comment by bobslee** [comment]
Hi @dustundag, any chance to test and report whether solved?

**Comment by bobslee** [comment]
Please re-open and comment if the issue persists.
