### ISSUE TITLE
Issue  Uninstall and Install Effecting 

### ISSUE THREAD

**Issue by dustundag** [novacode-nl/odoo-formio#120]

**Comment by dustundag** [comment]
I get the folowin error message  "Missing Record"
Record does not exist or has been deleted.
(Record: formio.builder.js.options(1,), User: 2)

**Comment by bobslee** [comment]
@dustundag I analysed found the bug! Thanks!
After uninstall, there was still a system parameter left, see screenshot. How shabby from me!
Shall solve now / soon.

![image](https://user-images.githubusercontent.com/328803/106480710-f8208c80-64ab-11eb-8c4a-64c9071d397b.png)

**Comment by dustundag** [comment]
Versions were as folows 
local: 14.0.8.14 | Remote: 14.0.8.16 
Shall I  try the new version?

**Comment by bobslee** [comment]
@dustundag it's not solved yet. Please wait I'll push a change a.s.a.p.

**Comment by dustundag** [comment]
It does not let me go to the settings as  i get the same error message
I will reboot and see if this error disappears. Alternatively restore previous vm snapshot couple of days ago

**Comment by bobslee** [comment]
As a quick workaround, you could delete the causing record by SQL:

`DELETE FROM ir_config_parameter WHERE key = 'formio.default_builder_js_options_id';`

**Comment by bobslee** [comment]
@dustundag  fixed in version **8.17** of the module. 
Also available for download: https://apps.odoo.com/apps/modules/14.0/formio/
Please replace on your server.

**Comment by dustundag** [comment]
Thanks
