### ISSUE TITLE
How to now add fields from custom modules ?

### ISSUE THREAD

**Issue by azmykn** [novacode-nl/odoo-formio#137]
I have a custom module and i want to know how to create form using it's fields ? 

I added my module as "Resource Model" , but when i created the field i don't know what i have to enter here " Property Name
".

**Comment by bobslee** [comment]
Hi, I don't understand your question yet.
Please provide a good description or example.

**Comment by bobslee** [comment]
@azmykn Please provide more info.

**Comment by azmykn** [comment]
> 
> 
> @azmykn Please provide more info.

Sorry bro , 
I have module to receive appointments and want to create form to receive appointments from visitors , but i don't know  to use this module to link fields in the form with fields in my appointment module.

**Comment by bobslee** [comment]
@azmykn Thanks for clarification. 

Unfortunately there's no configurable mapping between a form and other Odoo model yet.
There're plans to develop such a module. But we don't have an incentive yet. 

So for now you'll need to write some Python code in custom module or automated action to get this done. 
Use the module `formio_data_api`, which enables you to get all form data (values, labels) in an easy way. I shall document this soon on the Wiki here. 

If you need my help to implement your requirements, send me a message from the contact form on https://www.novacode.nl

Please close this issue if no further general questions.

Greets, Bob

**Comment by azmykn** [comment]
Thanks a lot , 
Will try this and waiting Wiki please ..
