### ISSUE TITLE
Question: Filter and Search records 

### ISSUE THREAD

**Issue by pyroit** [novacode-nl/odoo-formio#146]
First of all, amazing app for Odoo!!

I was playing around with the Demo version and in terms of data collection it seem to have endless opportunities. However, I am struggling when it comes analyzing, filtering and grouping the records. If can use the standard Odoo filters for the records self, but are not containing the form data itself. 

I few examples for use cases I am looking for:
- Overview of all Forms (the entries itself) in one table
- Grouping records according certain answers in the forms
- Able to filter according certain in the forms
- filter if certain attachment fields have attachments 

The only "work" around I found was to use the "Data" field and search for string
<img width="1387" alt="Screen Shot 2021-05-09 at 22 16 27" src="https://user-images.githubusercontent.com/9677935/117575447-619be100-b114-11eb-915e-b6b59699e409.png">
Picture in the demo system: https://demo13.novacode.nl/web#id=436&active_id=436&model=formio.form&view_type=formio_form&cids=1&menu_id=94

Is there are better to work with the records/forms? I appreciate any tips, Thank you very much

**Comment by bobslee** [comment]
Hi @pyroit, thanks for your kind words and trying the module.

Of course I understand your question and requirements.
Indeed, a Form's submission data is stored into one field `submission_data`.
That's why the **Forms ETL module** comes in.
Please visit it's apps page which has all info you'll need.

https://apps.odoo.com/apps/modules/14.0/formio_etl/

The ETL module currently doesn't support all Formio components. But if I'll get some incentive I would like to implement.

Let me know if you need any advice or help.

**Comment by pyroit** [comment]
Dear Bobslee, 
great i got it, thank you very much. That is exactly what I was looking for.
I have one more question if you do not mind.

I your demo version I added the following Form Buidler https://demo13.novacode.nl/web?#id=325&action=136&model=formio.builder&view_type=form&cids=1&menu_id=94
However when I try to "Create the Form Builder ETL Interface" I get the following error message:

Error:
Odoo Server Error

```
Traceback (most recent call last):
  File "/home/odoo/odoo/server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/odoo/server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/server/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/addons/subtree/odoo-formio-premium/formio_etl/wizard/formio_etl_wizard.py", line 40, in action_create
    etl = formio_etl.create_etl(self.builder_id)
  File "/home/odoo/odoo/addons/subtree/odoo-formio-premium/formio_etl/models/formio_etl.py", line 153, in create_etl
    'field_id': [(0, 0, vals) for vals in self._prepare_model_field_vals(builder_api)],
  File "/home/odoo/odoo/addons/subtree/odoo-formio-premium/formio_etl/models/formio_etl.py", line 363, in _prepare_model_field_vals
    for key, comp in builder_api.form_components.items():
AttributeError: 'Builder' object has no attribute 'form_components'

```

i am doing something wrong?

**Comment by bobslee** [comment]
Oh excuse me indeed.
I still need to change some internals, due to some renaming.
Shall do this a.s.a.p.

Because:

During last Friday's development sprint, we solved to transform complex nested Form structures (eg inside layouts, grids) into usable Python programming objects.
From now on the the PDF (QWeb) reports and Forms Data API can handle (almost) any complex Forms we'll be using.

**Comment by bobslee** [comment]
The intervals and changes reflect my following (formio) Python library: 

https://github.com/novacode-nl/python-formio-data

**Comment by pyroit** [comment]
Ok great I understand, so before installing the apps on our system should I wait or is the current live release not affected?

**Comment by bobslee** [comment]
Go ahead, no problem at all if you install the latest versions of the Odoo Apps and formio-data 0.0.3.

However I need to fix the `formio_etl` module, another client also needs this next week.
Of course, I also put its update on my demo env.

**Comment by bobslee** [comment]
Hi @pyroit, I just fixed the error in `formio_etl` (Forms ETL) module.
Also deployed the update on my https://demo13.novacode.nl.

Please let me know if still an issue, or close this one :)
Thanks!

**Comment by pyroit** [comment]
@bobslee nice, thank you very much for the quick fix. It works
