### ISSUE TITLE
[Question] How does one invoke onchange in formio component?

### ISSUE THREAD

**Issue by AdrianTeng** [novacode-nl/odoo-formio#159]
Thanks for the brilliant plugin!

I wish to accomplish something similar to Odoo's built-in `@api.onchange` function, namely, on outfocus of a text box component, it triggers a function (be it a python function on Odoo or a custom javascript function i define in the settings) that I could fetch data from other sources and fill it on the form.

Example: 
I have a form with 4 text fields: "email", "name", "phone", "country". When the user fill in the email, a call to a python function / javascript function should be made and search Odoo's `res.partner` for matching partner with same email; if found, use the first match and fill in name, phone, and country field.

If that's vanilla Odoo field, I would do:

```
@api.depends('email')
def _onchange_email_fill_fields(self):
    for rec in self:
        partner_id = self.env['res.partner'].sudo().search([('email', '=', rec.email)], limit=1)
        if partner_id:
            rec.name = partner_id.name
            rec.phone = partner_id.phone
            rec.country = partner_id.country_id.name
```

I've tried to achive this via the [data API](https://github.com/novacode-nl/odoo-formio/wiki/Populate-a-Form-Component-value,-with-data-from-Server-(Python)-Code) but it seems the ETL function is only invoked when the form is first loaded.

Any ideas how this could be done within the plugin without resort to injecting javascript in odoo built-in view?

**Comment by bobslee** [comment]
Hi @AdrianTeng 
Thanks for reaching out and considering this feature. 
Would be awesome if this is works out of the box.

Unfortunately I don't have any experience how to get this done.
Indeed, the `formio_data_api` only prepares and sends data from server to frontend.

I expect you need to hook the JS component somehow, if possible in elegant way.

I suggest to find similar feature request, to hook event (eg onchange) in Form Builder, in the GitHub issues https://github.com/formio/formio.js

Let me know if you found more info, so we're able to integrate with Odoo (server endpoint).

**Comment by bobslee** [comment]
@AdrianTeng I've an idea how to accomplish this with a nice and configurable API. But this requires some development effort.

Are you able to develop this, with a PR, when I assist you with the design approach.
If you'd like me to develop this, send me a mail to discuss:
bob (at) novacode (dot) nl

**Comment by bobslee** [comment]
@AdrianTeng your feature request is possible with the module:
https://apps.odoo.com/apps/modules/15.0/formio_components_api/
