### ISSUE TITLE
intalling error idk please help

### ISSUE THREAD

**Issue by zloslawa** [novacode-nl/odoo-formio#162]
what is this? i've installed python library and all and still get this:

Błąd:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/web/controllers/main.py", line 1745, in run
    result = action.run()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/website/models/ir_actions.py", line 61, in _run_action_code_multi
    res = super(ServerAction, self)._run_action_code_multi(eval_context)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'odoo.tools.convert.ParseError'>: "while parsing /bitnami/odoo/data/addons/14.0/formio/views/formio_builder_views.xml:50, near
<record id="view_formio_builder_form" model="ir.ui.view">
        <field name="name">formio.builder.form</field>
        <field name="model">formio.builder</field>
        <field name="arch" type="xml">
	    <form string="Form Builders">
                <header>
                    <button name="action_current" type="object" string="Current" attrs="{'invisible': [('state', 'in', ['CURRENT', 'OBSOLETE'])]}" class="btn-primary"/>
                    <button name="action_draft" type="object" string="Draft" attrs="{'invisible': [('state', 'in', ['DRAFT'])]}" confirm="Are you sure? Modifying the Form Builder causes existing forms to be invalid."/>
                    <button name="action_obsolete" type="object" string="Obsolete" attrs="{'invisible': [('state', '=', 'OBSOLETE')]}" confirm="Are you sure? The Form shall be unpublished."/>
                    <button name="action_new_builder_version" type="object" attrs="{'invisible':[('id','=',False)]}" string="Create New Version" class="oe_stat_button"/>
                    <field name="state" widget="statusbar"/>
                </header>
                <sheet>
                    <div class="oe_button_box" name="button_box">
                        <button name="action_view_formio" type="object" string="Form Builder" groups="formio.group_formio_admin" class="oe_stat_button" icon="fa-rocket"/>
                    </div>
                    <label for="title" class="oe_edit_only"/>
                    <h1><field name="title" placeholder="Insert a meaningful title here"/></h1>
                    <group>
                        <group>
                            <field name="name" placeholder="Use ASCII letters, digits (0-9), - or _" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                            <field name="version"/>
                            <field name="version_comment" attrs="{'required': [('version', '&gt;', 1)]}"/>
                            <field name="parent_id" string="Parent Version"/>
                        </group>
                        <group>
                            <field name="uuid" attrs="{'invisible': [('id', '=', False)]}"/>
                            <field name="user_id"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="General" name="settings">
                            <group name="settings">
                                <group name="formio_settings" string="formio.js">
                                    <field name="formio_version_id" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="wizard" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="wizard_on_next_page_save_draft" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="view_as_html" groups="formio.group_formio_admin"/>
                                </group>
                                <group string="Publish">
                                    <field name="portal" groups="formio.group_formio_admin" string="Publish on Portal"/>
                                    <field name="public" groups="formio.group_formio_admin" string="Publish to Public"/>
                                    <div class="text-muted" colspan="2">
                                        <i class="fa fa-info-circle" title="info"/> Configure in related tabs (Portal, Public / Website)
                                    </div>
                                </group>
                                <group name="integration_settings" string="Integration">
                                    <field name="formio_res_model_id" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}" edit="false" create="false" quick_create="false" options="{'no_create': True, 'no_create_edit':True, 'no_open': True}"/>
                                    <field name="res_model" attrs="{'invisible': [('formio_res_model_id', '=', False)]}"/>
                                    <div class="text-muted" colspan="2">
                                        <i class="fa fa-info-circle" title="info"/> Configure in Resource tab (if settings are available)
                                    </div>
                                    <div class="text-muted" colspan="2">
                                        <i class="fa fa-info-circle" title="info"/> This doesn't make any sense with Public (published) Forms, which are standalone.
                                    </div>
                                </group>
                                <group name="form_settings" string="Form Appearance">
                                    <field name="show_form_title" string="Show Title" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="show_form_state" string="Show State" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="show_form_user_metadata" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="show_form_id" string="Show ID" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="show_form_uuid" string="Show UUID" groups="formio.group_formio_admin" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                </group>

                                <field name="description" placeholder="Description..." groups="formio.group_formio_admin"/>
                            </group>
                            <div class="mb-3 text-muted">
                                <i class="fa fa-info-circle" title="info"/><strong> View as HTML</strong> - This setting (still) doesn't work since version 4.x<br/>
                                For more info see formio.js GitHub issue: <a href="https://github.com/formio/formio.js/issues/1545" target="_blank">select component rendering error in viewAsHtml model #1545</a><br/>
                                <i class="fa fa-info-circle" title="info"/><strong> Integration / Resource settings</strong> - Enables integration of Form and ERP/Odoo objects.<br/>
                            </div>
                        </page>
                        <page string="Resource" name="res_model_settings" attrs="{'invisible': [('formio_res_model_id', '=', False)]}"/>
                        <page string="Portal" name="portal_settings">
                            <group>
                                <group string="Redirect After Submit">
                                    <field name="portal_submit_done_url" groups="formio.group_formio_admin" string="Redirect URL" readonly="0"/>
                                </group>
                            </group>
                        </page>
                        <page string="Public" name="public_settings">
                            <div class="text-muted" colspan="2">
                                <i class="fa fa-info-circle" title="info"/> Configuration of Website features shall also be done here.
                            </div>
                            <group>
                                <group name="public_url" colspan="2" attrs="{'invisible': [('public_url', '=', False)]}">
                                    <field name="public_url" widget="CopyClipboardChar" style="font-size: 1.0em;"/>
                                </group>
                                <group name="general" string="General">
                                    <label for="public_access_interval_number" string="Expire After"/>
                                    <div>
                                        <field name="public_access_interval_number" class="oe_inline" groups="formio.group_formio_admin" attrs="{'required': [('public', '=', True)]}"/>
                                        <field name="public_access_interval_type" class="oe_inline ml-2" groups="formio.group_formio_admin" attrs="{'required': [('public', '=', True)]}"/>
                                    </div>
                                    <div class="text-muted" colspan="2">
                                        <i class="fa fa-info-circle" title="info"/><strong> Expire After:</strong> - Applicable on the Form it's (datimetime field) <strong>Public Access From</strong>.
                                    </div>
                                </group>
                                <group string="Redirect After Submit">
                                    <field name="public_submit_done_url" groups="formio.group_formio_admin" string="Redirect URL" readonly="0"/>
                                </group>
                            </group>
                        </page>
                        <page string="Components API" name="formio_components_api">
                            <group string="Partner" name="partner" colspan="2">
                                <div class="mb-2" colspan="2">
                                    <i class="fa fa-info-circle" title="info"/> To create or link (existing) Partner with a Form submission, specify the fields (Email, Name) from the Components API / Property Names.<br/>
                                    Partner determination/match shall be done by Email. This API is especially useful for public Forms.
                                </div>
                                <group>
                                    <field name="component_partner_email" string="Email" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="component_partner_name" string="Name" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                </group>
                                <group>
                                    <field name="component_partner_add_follower" string="Add to Followers" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                    <field name="component_partner_activity_user_id" string="Activity User" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                                </group>
                            </group>
                        </page>
                        <page string="Translations" name="translations" groups="formio.group_formio_admin">
                            <group>
                                <field name="language_en_enable"/>
                            </group>
                            <field name="translations" context="{'default_builder_id': id}">
                                <tree editable="bottom">
                                    <field name="builder_id" invisible="1"/>
                                    <field name="lang_id"/>
                                    <field name="source"/>
                                    <field name="value"/>
                                </tree>
                            </field>
                        </page>
                        <page string="Forms Permissions" name="forms_permissions" groups="formio.group_formio_admin">
                            <div class="mb-3 text-muted">
                                <i class="fa fa-info-circle" title="info"/> Specific permissions on Forms
                            </div>
                            <group>
                                <field name="allow_force_update_state_group_ids"/>
                            </group>
                            <group name="actions_settings" string="Actions">
                                <field name="form_allow_copy" groups="formio.group_formio_admin"/>
                                <field name="form_copy_to_current" groups="formio.group_formio_admin" attrs="{'invisible': [('form_allow_copy', '=', False)]}"/>
                            </group>
                        </page>
                        <page string="JS Options" name="javascript_options" groups="formio.group_formio_admin">
                            <div style="background-color: #e9ecef; padding: 0 10px;">
                                <group>
                                    <field name="formio_js_options_id" string="Select formio.js Options" attrs="{'readonly': [('state', '!=', 'DRAFT')]}" style="height: 100%"/>
                                </group>
                            </div>
                            
                            <field name="formio_js_options" placeholder="{ ... }" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                            <div class="text-muted mt-4">
                                <i class="fa fa-info-circle" title="info"/><strong> Documentation</strong><br/>
                                For example, Options could contain the Form Builder editForm with some File component settings:<br/>
                                <a href="https://github.com/formio/formio.js/blob/master/src/components/file/editForm/File.edit.file.js" target="_blank">
                                    https://github.com/formio/formio.js/blob/master/src/components/file/editForm/File.edit.file.js
                                </a>
                            </div>
                            <div>
                                <pre style="background-color: #e9ecef;">{
  'editForm': {
    'file': [
      {
        'key': 'file',
        'components': [
          {'key': 'webcam', 'defaultValue': True},
          {'key': 'storage', 'defaultValue': 'base64'}
        ]
      }
    ]
  }
}</pre>
                            </div>
                        </page>
                        <page string="JSON Schema" name="schema" groups="formio.group_formio_admin">
                            <field name="schema" attrs="{'readonly': [('state', '!=', 'DRAFT')]}"/>
                        </page>
                    </notebook>
                </sheet>
                <div class="oe_chatter" groups="formio.group_formio_admin">
                    <field name="message_follower_ids" widget="mail_followers"/>
                    <field name="activity_ids" widget="mail_activity"/>
                    <field name="message_ids" widget="mail_thread"/>
                </div>
            </form>
        </field>
    </record>" while evaluating
'records.button_immediate_install()'

**Comment by bobslee** [comment]
Why install php ?
Odoo and this module doesn't require php.

**Comment by zloslawa** [comment]
I did it, cause during installing formio i got pop-ups that said i need to install python library (mistake in my question)

**Comment by bobslee** [comment]
Sorry I don't have a clue about this issue.
I'm able to install on a clean/new database.

You've any suggestion about your particular setup?

**Comment by zloslawa** [comment]
:( I have odoo 14 bitnami on google cloud

**Comment by zloslawa** [comment]
Hello, sorry, i didn't have notice on this chain. Problem is that i don't
have a view of "open record" also, after adding "*Forms | Create Backend
Records*"  my form stopped recording data and performing redirect to page
on submit. My form is here http://34.142.116.69/rekrutacja-online

I can give you a dev login to my odoo to check it out.

Best regards

śr., 13 paź 2021 o 22:10 Bob Leers ***@***.***> napisał(a):

**Comment by bobslee** [comment]
@zloslawa please send me a message on my website contact form.
https://www.novacode.nl/nl/contactus

Leave your email address, I'll respond.

**Comment by bobslee** [comment]
Hey,

No prob, we’re catching up now.

I don’t understand your specific question yet. 
Please describe with more details.


Best Regards,

Bob Leers

Nova Code | Odoo Development & Consultancy
M: ***@***.***
W: https://www.novacode.nl
