### ISSUE TITLE
Table component not printed within reports. 

### ISSUE THREAD

**Issue by Home-Based** [novacode-nl/odoo-formio#171]
Hi All,

When attempting to render / print a form with a table component, the components within the table are not rendered.

Steps to reproduce :

1. Create a table in a form.
2. Fill the cells with a content component.
3. Submit the form.
4. Print the form. 

The table will not show on the produced pdf report.

Observations : The table is recognized by the renderer : the component "table" exists on an html report. But only empty rows are detected. The next foreach loop that has to detect the cells and their content for each row seems not to trigger, because the rows are empty. The "Table empty rows" form [370] in the Novacode "demo/demo" Odoo illustrates all this.

Regards,

Seb

**Comment by bobslee** [comment]
Hi Seb,
Ok indeed an issue, I see on the demo.
If your or somebody could submit a PR, I would like to test, review and merge.
Otherwise it depends on my spare time (not soon) to solve this issue.

**Comment by bobslee** [comment]
Solved in module `formio_report_qweb‘ version 5.0

Also update the Python library: `formio-data`
