### ISSUE TITLE
formio CRM lead not created

### ISSUE THREAD

**Issue by troymroberts** [novacode-nl/odoo-formio#187]
I have created a corm and assigned it to the CRM resource model.

However when forms are successfully summitted, the relevant leads/opportunities are not created in the CRM

**Comment by bobslee** [comment]
The resource model only ensures the form is available behind "Forms" smartbutton, eg in CRM Lead. 

Such integration, eg to create or update record could be implemented by automated action or custom module.

**Comment by troymroberts** [comment]
Ahhhh, i do have formio_crm installed. So the creation of the record isn't possible without further customization?

**Comment by bobslee** [comment]
Yes that's right.
