### ISSUE TITLE
Integration with recruitment module?

### ISSUE THREAD

**Issue by ni-ka** [novacode-nl/odoo-formio#194]
Has anyone tried to integrate this with the recruitment module? I find the default integration of survey module and recruitment quite basic. 

Thanks!

**Comment by bobslee** [comment]
Hi, I'm the author of this project. 

I don't know whether somebody integrated with the recruitment module(s).

However I expect it won't be too hard to develop a module for this.

**Comment by bobslee** [comment]
@ni-ka are you still interested in your topic?

Maybe we can collaborate.
Otherwise please close the issue.

Let me know, submit your message in my contact form: https://www.novacode.nl/contactus
