### ISSUE TITLE
Installing Problem - related to NL language ?

### ISSUE THREAD

**Issue by flexkeller** [novacode-nl/odoo-formio#195]
This is my entry on the Odoo-App-Store:

> by 
> Flex Keller
>  on 8/9/22, 12:09 PM [ Report](https://github.com/novacode-nl/odoo-formio/issues/new)
> I get the following error:
> 
> https://www.dropbox.com/s/hcuzfw2x731bwrb/Odoo-Formi-Error.txt?dl=0
> 
> it is too big to post here.
> 
> 
> 
> Re:
> by 
> Bob Leers
>  on 8/9/22, 2:40 PM Author [ Report](https://github.com/novacode-nl/odoo-formio/issues/new)
> Ok I see. 
> 
> Seems the external ID of the NL language can’t be found in your odoo installation.
> 
> Please could you submit a GitHub issue so I can analyse and follow up, reply from there?
> 
> https://github.com/novacode-nl/odoo-formio

I'm a bit confused... why do I need dutch language? My odoo is in german and english.
I have Odoo 13 running on docker.

Flex

**Comment by bobslee** [comment]
Hi, I shall have a look next week. 
Keep you posted.

**Comment by bobslee** [comment]
@flexkeller excuse me my answer delayed. I shall let you know soon.

**Comment by bobslee** [comment]
Hi @flexkeller ,
There should be an issue with your Odoo setup and not the **formio** module.

See the screenshot below, with explanation:
All possible languages should be present in the database (language model table).
However after new database creation, only the selected language (or US/English) is **active**, while others remain inactive.
The inactive languages are still usable, for example by references in code, other modules like the **formio** one.

So in my opinion, this issue can be closed. Do you agree?

![image](https://user-images.githubusercontent.com/328803/192459490-7aaf4b3f-06f0-44c1-94f2-8f8ad267d5e8.png)


By the way, the languages (records data) are located in following CSV and installed as not active by default.
https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/data/res.lang.csv

The dutch CSV row:
```csv
"base.lang_nl","Dutch / Nederlands","nl_NL","nl","Left-to-Right","[3,0]",",",".","%d-%m-%Y","%H:%M:%S","1"
```

**Comment by bobslee** [comment]
@flexkeller , by the way... 
I just created/installed a new and empty database with only German language and country.
No issue here, when I only install the **formio** module.

**Comment by bobslee** [comment]
Closed due to no answer.
