### ISSUE TITLE
Does this module need an (On premise) license from FormIO?

### ISSUE THREAD

**Issue by ehabmosilhy** [novacode-nl/odoo-formio#197]
Does this module need an (On premise) license from FormIO?
Because I can't have it run.
And keeps showing (Pending) message.

**Comment by bobslee** [comment]
What do you mean by:
1. `... (On premise) license from FormIO?`
2. `...keeps showing (Pending) message.` - Is it in Odoo or ?
3. Which Odoo version you use?

**Comment by ehabmosilhy** [comment]
Thanks for your answer, it's working now.

But still, I don't fully understand the license issue.
What I mean is that the company (FormIO) does only allow limited features when installed on premise. For example, you can't have an anonymous endpoint for entering data in the forms. We have to pay for some license to allow full features in local installations.

The great module that you have developed is working well but I'm still confused about this license issue. Is there really no need for a paid license?

**Comment by bobslee** [comment]
Let me know if following explanation answers your question.

In the Odoo module, only the MIT licensed “formio.js” (see link) JavaScript frontend library is imported from GitHub releases.
This ensures a Form Builder and Form can be rendered after fetching its required (JSON) data from Odoo endpoints (the is data stored in Odoo models/tables).

https://github.com/formio/formio.js

Do you need the features of their form.io (company) platform?
So this ain't possible now, there's no integration with the Odoo module and their platform.

**Comment by bobslee** [comment]
It would probably be an improvement in the module, when some parts (settings) in the Form Builder components will be removed, which ain't apply in Odoo.
Maybe a consideration for future work.

**Comment by ehabmosilhy** [comment]
Thanks for the great answer!
