### ISSUE TITLE
[v11][AccessRights] Create form with access rights: "User: All forms"

### ISSUE THREAD

**Issue by lieblinger** [novacode-nl/odoo-formio#21]
When a user with the **"User: All forms"** rights wants to to save the formio.form view or move from formio.form view to the formbuilder, odoo raises:

> 2020-03-10 19:21:24,385 6903 INFO odoo_formio odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: write, uid: 5, model: formio.builder

Is it wanted that non admin users, can't write a new form from an already present formbuilder template?

**Comment by bobslee** [comment]
hi @lieblinger 
ATM I couldn't find any clue regarding this issue. Also in a lack of time currently.
By any case it's not allowed that regular `formio.form` users can write on a `formio.builder` record/object.

Please could you investigate this further?
Maybe you can debug with the setting in the Odoo configfile: `log_level = debug_sql`

**Comment by lieblinger** [comment]
The log_level was very helpful!

Something tries to update the portal field in formio_builder table:
```
2020-03-17 17:51:17,980 7327 DEBUG odoo_formio odoo.sql_db: query: UPDATE "formio_builder" SET "portal"=%s,"write_uid"=%s,"write_date"=(now() at time zone 'UTC') WHERE id IN %s
```

**Comment by bobslee** [comment]
@lieblinger please update your git clone and test.
I reproduced the problem and seems solved now.
Awaiting for your answer.

**Comment by bobslee** [comment]
By the way @lieblinger, great finding in the logile!
Thank you! Much appreciated!

**Comment by lieblinger** [comment]
It's working great now. Last commit resolved the issue.
Thanks Bob!
