### ISSUE TITLE
is posible print automtically a form after a public user submit the form?

### ISSUE THREAD

**Issue by Destripador** [novacode-nl/odoo-formio#219]
my question is it posible print a pdf after a user submit the form

**Comment by bobslee** [comment]
Yes, you need the module:
https://apps.odoo.com/apps/modules/15.0/formio_report_qweb/

Or your question was about how to automatically print and email it to the person who submitted the form?
Which requirements do you have?
Is this a website form?

**Comment by Destripador** [comment]
Thanks for responds.

I have that module, but in a public forms is ́n possible print after a public user send, like a copy for the public user.

are you  have any idea?

**Comment by bobslee** [comment]
Yes that will be possible, by implementing an automated action (or some custom module).
Upon create of form record, you can send an email with the PDF attached.

If you need further support, contact me on: https://www.novacode.nl/contact
Please close issue when l the answer is ok.

**Comment by Destripador** [comment]
i made a module who do what i need.

I share it with you in case it is of your interest.


https://github.com/Destripador/formio_report_public/tree/main

**Comment by bobslee** [comment]
Thanks for your message and sharing. 
You need to cleanup and format your module a bit :)

Actually I don't see any need for public access to forms reports, because of privacy and legislation concerns etc.
Sharing reports could still be provided in different ways, eg by using Odoo enterprise Documents module/app.
