### ISSUE TITLE
hello I have some questions regarding PDF print for formio forms 

### ISSUE THREAD

**Issue by armasaru-denis** [novacode-nl/odoo-formio#222]
First of all I use Odoo 15 and installed formio.j version si 5.0.0-rc4 .
When I use Tree Component in form builder it acts as aspected in portal and draft mode, but in print (regardless of completion) it dosent show. Is this a bug ?

**Comment by bobslee** [comment]
What do you mean by "print" ?

Is that the printing of the PDF, by the `formio_report_qweb` module?
In that case, the Tree component isn't implemented yet.

**Comment by bobslee** [comment]
Also be aware, the `formio_storage_filestore` module doesn't wortk with formio.js v5.0.0-rc4.
The formio.js throws a JS error when using the (File) URL provider.

**Comment by armasaru-denis** [comment]
yes it is  formio_report_qweb

**Comment by bobslee** [comment]
If you need the Tree component in the QWeb report (module), 2 development efforts need to be done:

1. Implement the Tree component in underlying `formio-data` Python library:
https://github.com/novacode-nl/python-formio-data

2. Implement the Tree component in the `formio_report_qweb` QWeb components xml:
https://github.com/novacode-nl/odoo-formio/blob/15.0/formio_report_qweb/report/report_formio_form_components.xml

Of course you can submit a PR.
If you'd like me to implement this request, submit your request on https://www.novacode.nl/contact
So we can discuss and follow up.

**Comment by bobslee** [comment]
@armasaru-denis Is still needed?
Otherwise please close the issue. 
It's a feature request :)
