### ISSUE TITLE
I have an issue Regarding Submiting forms 

### ISSUE THREAD

**Issue by armasaru-denis** [novacode-nl/odoo-formio#224]
Abstract:
 I am trying to make a form that has nested Data Grid Components ,one inside another.
 --version of odoo is 15
 --Installed formio.js version 4.15.0-rc.21
 --Forms module Latest Version 15.0.11.11

Current situation: 
After setting up the form in form builder as shown in video, I then make a form I fill it and press submit. The form is not sent, the submission button keeps loading.

https://github.com/novacode-nl/odoo-formio/assets/77189160/f3ef2973-923c-4d58-952d-e60bf6af6de1

https://github.com/novacode-nl/odoo-formio/assets/77189160/7f001a84-2a24-4b43-bd30-9593ac3440d9

Based on the type of browsers there are different errors.

The errors in console in Chrome and Opera are :

```
Ucaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at formio_form.js:167:29
    at formio.full.min.js:2:1130894
    at Array.forEach (<anonymous>)
    at b (formio.full.min.js:2:1130472)
    at Boolean.<anonymous> (formio.full.min.js:2:1131217)
    at Array.forEach (<anonymous>)
    at formio.full.min.js:2:1131189
    at Array.forEach (<anonymous>)
    at Object.b (formio.full.min.js:2:1130472)
    at formio_form.js:165:25
DevTools failed to load source map: Could not load content for https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/formio/static/lib/bootstrap/4.1.3/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

<img width="923" alt="image" src="https://github.com/novacode-nl/odoo-formio/assets/77189160/6a1284bc-701f-4c15-a420-e14a93d15337">

The errors in console in FireFox are :

```
Some cookies are misusing the recommended “SameSite“ attribute 4
Uncaught (in promise) TypeError: compObj is undefined
    createForm https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/formio/static/src/js/form/formio_form.js:167
    b https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/web/content/364/formio.full.min.js:2
    b https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/web/content/364/formio.full.min.js:2
    b https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/web/content/364/formio.full.min.js:2
    b https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/web/content/364/formio.full.min.js:2
    b https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/web/content/364/formio.full.min.js:2
    createForm https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/formio/static/src/js/form/formio_form.js:165
[formio_form.js:167:21](https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/formio/static/src/js/form/formio_form.js)
Source map error: Error: request failed with status 404
Resource URL: https://odooinsightorg-test-v15-multicomp-prod-formio.odoo.com/formio/static/lib/bootstrap/4.1.3/bootstrap.min.css
Source Map URL: bootstrap.min.css.map
```

<img width="1054" alt="Screenshot 2023-05-11 145602" src="https://github.com/novacode-nl/odoo-formio/assets/77189160/82a78d9d-0d6a-40f9-8a20-26fc1cca4561">

The same situation arises when I try a Tree Component inside a Data Grid component as seen in video:

https://github.com/novacode-nl/odoo-formio/assets/77189160/67dc0e49-5daa-4b04-b3ac-ddc57634bf64

Desired situation: Submition completed.

**Comment by bobslee** [comment]
Thanks for reporting the issue with extensive info and screen recordings!

The lack of the `bootstrap.css.map` (source map) file occurred to me. 
However I didn't experienced or expect this lead to an issue. 

Are you able to upgrade (on a dev, test server) the base Forms (`formio`) module to the latest version?

Since 15.0.12.0 this provides a new model and feature "Extra Assets", which enables you to add the `bootstrap.css.map` file manually. 
So you can check whether the issue shall be resolved when loading that source map file. 

Awaiting on your answer.

**Comment by bobslee** [comment]
Actually, you can also add the source map file to the `formio.version` assets. 

So you don't need to upgrade the module.

But I won't recommended that approach.

**Comment by armasaru-denis** [comment]
Update: 

--version of odoo is 15
--Installed formio.js version 4.15.0-rc.22
--Forms module Latest Version 15.0.12.11

I have changed the source-map (.css.map) . As it is, the bootstrap error below does ot apear anymore :
<img width="934" alt="238360921-b0b8677b-80eb-4e84-a7e7-ea334c886287" src="https://github.com/novacode-nl/odoo-formio/assets/77189160/192b5821-eb28-4328-ae2b-a7d4b7cfd5c0">

Even so, the form is still not working the error might be in the js logic or the reading of the js file. 
<img width="929" alt="image" src="https://github.com/novacode-nl/odoo-formio/assets/77189160/6e09d237-29d7-4be9-a693-3edfb6ae205f">

This is the JSON Schema of the form that i'm trying to make : 

`{"components":` [{"label": "Data Grid Parent", "labelPosition": "top", "description": "", "tooltip": "", "disableAddingRemovingRows": false, "conditionalAddButton": "", "reorder": false, "addAnother": "", "addAnotherPosition": "bottom", "layoutFixed": false, "enableRowGroups": false, "initEmpty": false, "customClass": "", "tabindex": "", "hidden": false, "hideLabel": false, "autofocus": false, "disabled": false, "tableView": false, "modalEdit": false, "defaultValue": [{"textFieldParentData": "", "dataGridParent1": [{"textFieldParentData1": ""}]}], "persistent": true, "protected": false, "dbIndex": false, "encrypted": false, "redrawOn": "", "clearOnHide": true, "customDefaultValue": "", "calculateValue": "", "calculateServer": true, "allowCalculateOverride": false, "validateOn": "change", "validate": {"required": false, "minLength": "", "maxLength": "", "customMessage": "", "custom": "", "customPrivate": false, "json": "", "strictDateValidation": false, "multiple": false, "unique": false}, "errorLabel": "", "errors": "", "key": "dataGridParent", "tags": [], "properties": {}, "conditional": {"show": null, "when": null, "eq": "", "json": ""}, "customConditional": "", "logic": [], "attributes": {}, "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""}, "type": "datagrid", "input": true, "components": [{"label": "Text Field parent data", "applyMaskOn": "change", "tableView": true, "key": "textFieldParentData", "type": "textfield", "input": true, "id": "e6ip4qq", "placeholder": "", "prefix": "", "customClass": "", "suffix": "", "multiple": false, "defaultValue": null, "protected": false, "unique": false, "persistent": true, "hidden": false, "clearOnHide": true, "refreshOn": "", "redrawOn": "", "modalEdit": false, "dataGridLabel": false, "labelPosition": "top", "description": "", "errorLabel": "", "tooltip": "", "hideLabel": false, "tabindex": "", "disabled": false, "autofocus": false, "dbIndex": false, "customDefaultValue": "", "calculateValue": "", "calculateServer": false, "widget": {"type": "input"}, "attributes": {}, "validateOn": "change", "validate": {"required": false, "custom": "", "customPrivate": false, "strictDateValidation": false, "multiple": false, "unique": false, "minLength": "", "maxLength": "", "pattern": ""}, "conditional": {"show": null, "when": null, "eq": ""}, "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""}, "allowCalculateOverride": false, "encrypted": false, "showCharCount": false, "showWordCount": false, "properties": {}, "allowMultipleMasks": false, "addons": [], "mask": false, "inputType": "text", "inputFormat": "plain", "inputMask": "", "displayMask": "", "spellcheck": true, "truncateMultipleSpaces": false}, {"label": "Data Grid Child", "reorder": false, "addAnotherPosition": "bottom", "layoutFixed": false, "enableRowGroups": false, "initEmpty": false, "tableView": false, "defaultValue": [{"textFieldParentData1": ""}], "calculateServer": true, "key": "dataGridParent1", "type": "datagrid", "input": true, "components": [{"label": "Text Field Child parent data", "applyMaskOn": "change", "tableView": true, "key": "textFieldParentData1", "type": "textfield", "input": true, "id": "e7sxttl", "placeholder": "", "prefix": "", "customClass": "", "suffix": "", "multiple": false, "defaultValue": null, "protected": false, "unique": false, "persistent": true, "hidden": false, "clearOnHide": true, "refreshOn": "", "redrawOn": "", "modalEdit": false, "dataGridLabel": false, "labelPosition": "top", "description": "", "errorLabel": "", "tooltip": "", "hideLabel": false, "tabindex": "", "disabled": false, "autofocus": false, "dbIndex": false, "customDefaultValue": "", "calculateValue": "", "calculateServer": false, "widget": {"type": "input"}, "attributes": {}, "validateOn": "change", "validate": {"required": false, "custom": "", "customPrivate": false, "strictDateValidation": false, "multiple": false, "unique": false, "minLength": "", "maxLength": "", "pattern": ""}, "conditional": {"show": null, "when": null, "eq": ""}, "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""}, "allowCalculateOverride": false, "encrypted": false, "showCharCount": false, "showWordCount": false, "properties": {}, "allowMultipleMasks": false, "addons": [], "mask": false, "inputType": "text", "inputFormat": "plain", "inputMask": "", "displayMask": "", "spellcheck": true, "truncateMultipleSpaces": false}], "id": "edvtqui", "placeholder": "", "prefix": "", "customClass": "", "suffix": "", "multiple": false, "protected": false, "unique": false, "persistent": true, "hidden": false, "clearOnHide": true, "refreshOn": "", "redrawOn": "", "modalEdit": false, "dataGridLabel": false, "labelPosition": "top", "description": "", "errorLabel": "", "tooltip": "", "hideLabel": false, "tabindex": "", "disabled": false, "autofocus": false, "dbIndex": false, "customDefaultValue": "", "calculateValue": "", "widget": null, "attributes": {}, "validateOn": "change", "validate": {"required": false, "custom": "", "customPrivate": false, "strictDateValidation": false, "multiple": false, "unique": false}, "conditional": {"show": null, "when": null, "eq": ""}, "overlay": {"style": "", "left": "", "top": "", "width": "", "height": ""}, "allowCalculateOverride": false, "encrypted": false, "showCharCount": false, "showWordCount": false, "properties": {}, "allowMultipleMasks": false, "addons": [], "tree": true, "lazyLoad": false, "disableAddingRemovingRows": false}], "placeholder": "", "prefix": "", "suffix": "", "multiple": false, "unique": false, "refreshOn": "", "dataGridLabel": false, "widget": null, "showCharCount": false, "showWordCount": false, "allowMultipleMasks": false, "addons": [], "tree": true, "lazyLoad": false, "id": "efc02bm"}, {"label": "Submit", "action": "submit", "showValidations": false, "theme": "primary", "size": "md", "block": false, "leftIcon": "", "rightIcon": "", "shortcut": "", "description": "", "tooltip": "", "customClass": "", "tabindex": "", "disableOnInvalid": true, "hidden": false, "autofocus": false, "disabled": false, "tableView": false, "modalEdit": false, "key": "submit", "tags": [], "properties": {}, "conditional": {"show": null, "when": null, "eq": "", "json": ""}, "customConditional": "", "logic": [], "attributes": {}, "overlay": {"style": "", "page": "", "left": "", "top": "", "width": "", "height": ""}, "type": "button", "input": true, "placeholder": "", "prefix": "", "suffix": "", "multiple": false, "defaultValue": null, "protected": false, "unique": false, "persistent": false, "clearOnHide": true, "refreshOn": "", "redrawOn": "", "dataGridLabel": true, "labelPosition": "top", "errorLabel": "", "hideLabel": false, "dbIndex": false, "customDefaultValue": "", "calculateValue": "", "calculateServer": false, "widget": {"type": "input"}, "validateOn": "change", "validate": {"required": false, "custom": "", "customPrivate": false, "strictDateValidation": false, "multiple": false, "unique": false}, "allowCalculateOverride": false, "encrypted": false, "showCharCount": false, "showWordCount": false, "allowMultipleMasks": false, "addons": [], "id": "e4objv"}]}`

Question : Does this form (JSON above) work on your setup?

**Comment by bobslee** [comment]
Hi @armasaru-denis 
Thanks for sharing the schema and info.
I just reproduced and fixed this issue!

The release/update has been pushed to this repo and in the Apps Store.
Let me know whether this solves it for you too :)

I would appreciate it if you leave a nice review: https://apps.odoo.com/apps/modules/16.0/formio/

**Comment by armasaru-denis** [comment]
Hello @bobslee  

Thank you for your prompt responses and quick engagement. I am happy to report that the remedies you have done are working for me as well. 

And of course, i am leaving a kind review. 
Have a nice day!
