### ISSUE TITLE
[FEATURE] PDF export

### ISSUE THREAD

**Issue by lieblinger** [novacode-nl/odoo-formio#25]
The ability to export pdf's from a formio.form, would be great feature.

@bobslee What do you think?

**Comment by bobslee** [comment]
hi @lieblinger, indeed, that would be a welcome feature!

A while ago that already came to my mind :)
Also somebody raised a similar question on the Odoo Apps Store page of the Formio module: [https://apps.odoo.com/apps/modules/12.0/formio](https://apps.odoo.com/apps/modules/12.0/formio)

Do you have a suggestion about the functionality or implementation approach?

The following was my answer and suggestion on the Odoo Apps Store page:

> Unfortunately, printing the form (builder/design, user form) isn't implemented yet. I suppose this could be implemented either by following approaches. Both take some effort in development. 
>
> 1. Implement the Form.io PDF rendering (Javascript) feature, if possible from the Javascript API. More info and research needed for this. 
> 2. Formio data available by the Odoo ORM, which can be used in Qweb reports, Automated Actions etc. This requires a "Python Formio (data) parser" (https://github.com/novacode-nl/python-formio-parser), which I put on hold. Also a Odoo module is needed to integrate the parser and make parser/data available by the Odoo ORM.

**Current status:**
Several months ago, I already made good progress with the (Python) Formio data parser and even the Odoo module to integrate.
In fact this enables implemenging Qweb reports for the Forms. So still no out-of-the-box PDF generation.

**Features:**
- For each Form Builder (version) it generates custom: model, views, access and menu.
- Upon create/update of a Form, it stores the record in the custom model.
- In list/tree view of custom model one is able to search.

However I need to implement and complete the basics and decide, before I push it online. Which takes quite some effort.

**Comment by lieblinger** [comment]
Hi @bobslee 
I've found a library on github, which looks very promissing.

https://github.com/multinerd/formio-export

Maybe it would be the easiest, If we create an "Export to PDF" button on forms which links to this model.

**Comment by bobslee** [comment]
Nice finding!
I searched such Formio projects from a while ago. Regarding PDF generation, CSV export etc.
Also came across this one, now I remember.

Please feel free and go ahead with research and creating a module if this could work out.
I noticed the formio export JS needs the components registered in into the `options` argument of into constructor?
Or it also works with specific components registration, for all components?

**Comment by lieblinger** [comment]
I've build a module with linked library. This module works so, far.

Later we should upgrade this module and add a wkhtmltopdf integration.

PR
https://github.com/novacode-nl/odoo-formio/pull/27

**Comment by bobslee** [comment]
Module `formio_report_qweb` provides this feature.

**Comment by lieblinger** [comment]
Thanks for providing these great features for odoo!
