### ISSUE TITLE
Forms | Website Integration Error on Odoo16

### ISSUE THREAD

**Issue by cpuvampier** [novacode-nl/odoo-formio#251]
On a fresh Odoo16 Installation after try to integrate a From into the WebSite

Uncaught Promise > QWeb2: Template 'website.prompt' not found

How can i solve this ?

**Comment by bobslee** [comment]
This is a technical (JS) issue.
However I'm not available to analyse/solve for a while now.

**Comment by cpuvampier** [comment]
Odoo Installation via Container Docker/Latest image.
 Client Error:
 
UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of undefined (reading 'writeText')

TypeError: Cannot read properties of undefined (reading 'writeText')
    at ClientErrorDialog.onClickClipboard (http://172.20.2.17/web/assets/1764-6733c89/web.assets_backend.min.js:620:48)
    at Object.mainEventHandler (http://172.20.2.17/web/assets/1763-647a30e/web.assets_common.min.js:1899:77)
    at HTMLButtonElement.listener (http://172.20.2.17/web/assets/1763-647a30e/web.assets_common.min.js:1134:15)

**Comment by cpuvampier** [comment]
Yes will occur when try to drop the Block
![Bildschirmfoto 2023-07-25 um 17 36 38](https://github.com/novacode-nl/odoo-formio/assets/79981143/7ea407e8-5810-4a60-93f8-c681ef06e9ea)

**Comment by bobslee** [comment]
Ok. 
That's a big effort to analyze and fix - I remember from the past.

I only will perform that with funding. 
You can discuss by leaving a message on the contact form https://www.novacode.nl/nl/contact

**Comment by bobslee** [comment]
Of course feel free to submit a PR.

**Comment by cpuvampier** [comment]
@bobslee Thank you, i had a question to understand. You may running also V16 ?
There are some pre-requirement to get this running on other Version. i guess you may got it running.
On what direction this error will point ? Backend or JS Frontend ?
I am asking myself, can i am the only one who run into this bug ?

**Comment by bobslee** [comment]
This is a JS frontend error, occurring since the Form app in Odoo V.16.
No you're not the only one running into this bug. But I don't have plans to fix this soon, without funding.

**Comment by bobslee** [comment]
@cpuvampier The website form snippet is available and working in Odoo 17.

You need the paid module:
https://apps.odoo.com/apps/modules/17.0/website_formio_snippet/

I close this issue.
