### ISSUE TITLE
Odoo 15 form submission not working

### ISSUE THREAD

**Issue by JGStyle** [novacode-nl/odoo-formio#255]
In a form, When I click submit, I get the green toast that says success but the redirection does not work. the submit button keeps spinning forever..
No submission appears in the backend.

I tested it on two odoo15 instances both produced the same result. 
One instance on localhost (testing)
One instance running via https: on a domain (production)

I have attached a screenshot demonstrating what it looks like.

I send the forms from the portal view.
Or maybe Is there just some configuration missing from my end?

<img width="640" alt="Bildschirmfoto 2023-09-01 um 11 52 13" src="https://github.com/novacode-nl/odoo-formio/assets/51161233/455057b6-8908-4712-81eb-f7c5f76b802f">

**Comment by JGStyle** [comment]
Note, I tested on version
15.0.16.5

**Comment by bobslee** [comment]
@JGStyle thanks for reporting. 
Should be **solved** now for Odoo v.15, v.16.

The cause was due to a regression in recent commit (few days ago).

Please close this issue when you confirm.

**Comment by bobslee** [comment]
@JGStyle of course update the `formio` module again.
Maybe refresh/clear browser cache as well.

**Comment by JGStyle** [comment]
Amazed by the quick solution.
Version 15.0.16.7 solves the issue.
