### ISSUE TITLE
[15.0][16.0] Dropping a Date / Time component to form prevent further changes in builder to be saved

### ISSUE THREAD

**Issue by BT-dmoreno** [novacode-nl/odoo-formio#261]
Currently observed in Odoo versions _15.0_ and _16.0_ and while using Formio version _4.16.0_.

**To reproduce:**
 - Create a new form builder, select a Text field component and drag it, save and come back, in this case everything should be fine.
 - Now, add a Date / Time field to the form, save and come back from the formio.builder, this time the Date / Time field will not be there, meaning that it was not saved.
 - Even more, if you drag a Date / Time field, and later, you continue editing the form with more fields and configurations. When you save and come back, everything is lost, this happens from the very first moment the Date / Time field was included in the form.
 
 Using auto-save or manual save of the builder while editing doesn't really matters.
 
 This can be observed directly for version 16.0 in the offitial [live preview page ](https://demo16.novacode.nl/web/login).

**Comment by bobslee** [comment]
Does this also occur with "formio.js version" 4.16.0 ?

**Comment by BT-dmoreno** [comment]
Yes, that is in fact the exact formio version that I was using.

**Comment by bobslee** [comment]
I just tested.
The issue doesn't occur with:
- Latest **formio** (Odoo) module version: `16.0.7.2`
- formio.js (library) version: `4.16.0`

![image](https://github.com/novacode-nl/odoo-formio/assets/328803/4ba90c6e-e63c-4937-b607-da5c3690725f)


QUESTIONS:

1. Do you use the same versions?

2. Also if it's the form builder from the demo environment(*) shown in the screenshot, I only see **formio.js version**  `5.0.0-rc.4`

![image](https://github.com/novacode-nl/odoo-formio/assets/328803/8da6a37c-1932-4b9f-a0f9-280a7d01fb57)

**Comment by bobslee** [comment]
Can you check the logs. Maybe you find out something over there.
- Odoo server log
- Browser console

**Comment by BT-dmoreno** [comment]
Closing this issue since I'm not able to reproduce it again in the test environment, and in local, after changing formio.js version to 4.16.0 also got solved.

Thanks a lot for your quick reply!

**Comment by bobslee** [comment]
Hi, you're welcome.
Glad it works. 

Does it also work on Odoo v.15 ?

**Comment by BT-dmoreno** [comment]
Yes, I've been checking it in Odoo version 15.0.
