### ISSUE TITLE
formio_ref not found in ir_act_server

### ISSUE THREAD

**Issue by tilleul** [novacode-nl/odoo-formio#263]
For who it might help:

Upgraded formio from v14.0.9.21 to v14.0.12.0 and got severe odoo server crash (restarted but refusing to display any page in http(s) ).

Logs in /var/log/odoo/odoo-server.log indicated problem with a field formio_ref not found in table ir_act_server.

I had to use psql directly and do `alter table ir_act_server add column formio_ref character varying;` to fix the issue.

I don't know where the problem is in the python scripts.

**Comment by bobslee** [comment]
@tilleul thanks for reporting.
I just analysed the `formio` module changelog. No actual cause found.
So maybe it's related to something on your side.
I close this issue now.
