### ISSUE TITLE
Error in update Formio

### ISSUE THREAD

**Issue by carlo-github** [novacode-nl/odoo-formio#264]
**Context**
Odoo.sh
Formio version: "16.0.6.7"

**Actual result**
Downloaded the module from https://apps.odoo.com/apps/modules/16.0/formio/ version "16.0.10.3"
and try to install, I got this log and the build is not created:

20/10/2023 16:50:15 | ERROR | server | bad query: SELECT "ir_model"."id" AS "id", "ir_model"."name"->>'en_US' AS "name", "ir_model"."model" AS "model", "ir_model"."order" AS "order", "ir_model"."info" AS "info", "ir_model"."state" AS "state", "ir_model"."transient" AS "transient", "ir_model"."create_uid" AS "create_uid", "ir_model"."create_date" AS "create_date", "ir_model"."write_uid" AS "write_uid", "ir_model"."write_date" AS "write_date", "ir_model"."is_mail_thread" AS "is_mail_thread", "ir_model"."is_mail_activity" AS "is_mail_activity", "ir_model"."is_mail_blacklist" AS "is_mail_blacklist", "ir_model"."abstract" AS "abstract", "ir_model"."ref_merge_ir_act_server_id" AS "ref_merge_ir_act_server_id" FROM "ir_model" WHERE "ir_model".id IN (1343) ERROR: column ir_model.abstract does not exist LINE 1: ...odel"."is_mail_blacklist" AS "is_mail_blacklist", "ir_model"...                                                              ^
-- | -- | -- | --
20/10/2023 16:50:15 | WARNING | server | Transient module states were reset
20/10/2023 16:50:15 | ERROR | server | Failed to load registry Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/api.py", line 989, in get     cache_value = field_cache[record._ids[0]] KeyError: 1343  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/fields.py", line 1160, in __get__     value = env.cache.get(record, self)   File "/home/odoo/src/odoo/odoo/api.py", line 996, in get     raise CacheMiss(record, field) odoo.exceptions.CacheMiss: 'ir.model(1343,).model'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root     f(rec)   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 599, in _tag_record     record = model._load_records([data], self.mode == 'update')   File "/home/odoo/src/odoo/odoo/models.py", line 4374, in _load_records     data['record']._load_records_write(data['values'])   File "/home/odoo/src/odoo/odoo/models.py", line 4305, in _load_records_write     self.write(values)   File "/home/odoo/src/odoo/addons/mail/models/res_groups.py", line 17, in write     res = super(ResGroups, self).write(vals)   File "/home/odoo/src/odoo/odoo/addons/base/models/res_users.py", line 1358, in write     res = super(GroupsView, self).write(values)   File "/home/odoo/src/odoo/odoo/addons/base/models/res_users.py", line 1234, in write     res = super(GroupsImplied, self).write(values)   File "/home/odoo/src/odoo/odoo/addons/base/models/res_users.py", line 225, in write     self.env['ir.model.access'].call_cache_clearing_methods()   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 1932, in call_cache_clearing_methods     self.env.invalidate_all()   File "/home/odoo/src/odoo/odoo/api.py", line 727, in invalidate_all     self.flush_all()   File "/home/odoo/src/odoo/odoo/api.py", line 737, in flush_all     self._recompute_all()   File "/home/odoo/src/odoo/odoo/api.py", line 733, in _recompute_all     self[field.model_name]._recompute_field(field)   File "/home/odoo/src/odoo/odoo/models.py", line 6199, in _recompute_field     field.recompute(records)   File "/home/odoo/src/odoo/odoo/fields.py", line 1365, in recompute     apply_except_missing(self.compute_value, recs)   File "/home/odoo/src/odoo/odoo/fields.py", line 1338, in apply_except_missing     func(records)   File "/home/odoo/src/odoo/odoo/fields.py", line 1387, in compute_value     records._compute_field_value(self)   File "/home/odoo/src/odoo/odoo/models.py", line 4221, in _compute_field_value     fields.determine(field.compute, self)   File "/home/odoo/src/odoo/odoo/fields.py", line 100, in determine     return needle(records, *args)   File "/home/odoo/src/odoo/odoo/fields.py", line 701, in _compute_related     record[self.name] = self._process_related(value[self.related_field.name])   File "/home/odoo/src/odoo/odoo/models.py", line 5897, in __getitem__     return self._fields[key].__get__(self, type(self))   File "/home/odoo/src/odoo/odoo/fields.py", line 1186, in __get__     recs._fetch_field(self)   File "/home/odoo/src/odoo/odoo/models.py", line 3190, in _fetch_field     self._read(fnames)   File "/home/odoo/src/odoo/odoo/models.py", line 3267, in _read     cr.execute(query_str, params + [sub_ids])   File "/home/odoo/src/odoo/odoo/sql_db.py", line 321, in execute     res = self._obj.execute(query, params) psycopg2.errors.UndefinedColumn: column ir_model.abstract does not exist LINE 1: ...odel"."is_mail_blacklist" AS "is_mail_blacklist", "ir_model"...                                                              ^   The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new     odoo.modules.load_modules(registry, force_demo, status, update_module)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 484, in load_modules     processed_modules += load_marked_modules(cr, graph,   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules     loaded, processed = load_module_graph(   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 231, in load_module_graph     load_data(cr, idref, mode, kind='data', package=package)   File "/home/odoo/src/odoo/odoo/modules/loading.py", line 71, in load_data     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 763, in convert_file     convert_xml_import(cr, module, fp, idref, mode, noupdate)   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import     obj.parse(doc.getroot())   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 749, in parse     self._tag_root(de)   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root     f(rec)   File "/home/odoo/src/odoo/odoo/tools/convert.py", line 711, in _tag_root     raise ParseError('while parsing %s:%s, somewhere inside\n%s' % ( odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/formio/security/formio_security.xml:12, somewhere inside <record id="group_formio_user" model="res.groups">             <field name="name">User: Assigned forms</field>             <field name="category_id" ref="base.module_category_forms_forms"/>             <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>         </record>

**Comment by bobslee** [comment]
Did you tried with the latest version 16.0.10.3 ?

**Comment by bobslee** [comment]
My bad, I see now you tried to upgrade.
Will analyse the log soon.

**Comment by bobslee** [comment]
Are you sure it's related with the "formio" module ?
I did several upgrades for clients/projects within 16.0. No issues experienced.

In your log I also notice something concerning `is_mail_blacklist`.
Could that be related ? You upgrade other modules as well ?

**Comment by carlo-github** [comment]
i try to update only formio module

**Comment by bobslee** [comment]
Ok. Unfortunately the issue isn't obvious to me. 
If you can point it out, please. 
Otherwise you can request a support package, to give us access to your Odoo.sh instance, so we can analyze and fix.

**Comment by elmehdibousstani** [comment]
para me tambem noa esta funcionando

**Comment by bobslee** [comment]
I can not reproduce your issue.

Check out the screencast: https://watch.screencastify.com/v/je4xtDczgAVOyGc2MAle

Actions in screencast:
- On a new Odoo 16.0 database
- Installed the Forms app with version 16.0.6.7
- Upgrade the Forms app to version 16.0.10.3
- App just works

Your experience may vary due to your setup:
As I mentoined in my previous answer. I don't know about your setup, other 3rd pary modules, customizations etc.
If you need support, I recommend a developer to check out your (Odoo.sh) server instance.

If no response is received, I will close this issue.

**Comment by bobslee** [comment]
@carlo-github Thanks for responding and sharing the info. 

Please contact us concerning the `formio_helpdesk` module, by submitting our contact form:

https://www.novacode.nl/contact

So we can fix and follow up with you.
