### ISSUE TITLE
Migration to odoo17

### ISSUE THREAD

**Issue by Abhishek-Wagh** [novacode-nl/odoo-formio#269]
Please could you let me know if there is any path for odoo17 migration already in action?

**Comment by bobslee** [comment]
@Abhishek-Wagh Yes absolutely!
When our schedule allows it, we 
prepare the release of the Forms app and related modules.
We expect we can release somewhere next month.

Please can you close this issue / question ?

**Comment by Abhishek-Wagh** [comment]
@bobslee Thanks for responding sharing the info.
