### ISSUE TITLE
Multi step forms ?

### ISSUE THREAD

**Issue by esakarya** [novacode-nl/odoo-formio#274]
its possible multi step forms ? can be questions categorise ?

**Comment by bobslee** [comment]
You can enable the wizard (field setting) in a form builder for multi step/page forms. 

This enables you to add statical pages/steps.

**Comment by bobslee** [comment]
@esakarya Any update? Or can you code this issue?

**Comment by esakarya** [comment]
Thanks for your support. i am done thank you
