### ISSUE TITLE
File uploads (Premium Components)

### ISSUE THREAD

**Issue by timnis** [novacode-nl/odoo-formio#281]
Hi,

Just installed and played little bit with odoo-formio and it looks great :smile: 
However I noticed that File upload is part of Formio Premium Components? Will it be functional also in future (without buying Formio Premium) in odoo-formio use (with formio_storage_filestore)?

-Timo

**Comment by bobslee** [comment]
@timnis The file upload is actually available.
By default a file upload is stored as Base64 in the `formio.form` database record.
The module `formio_storage_filestore` stores the file in the (Odoo) filestore and link as attachment with the `formio.form` record.

See the screenshot below for the file upload component configuration, using the `formio_storage_filestore` module.
Please close this issue if there're no related questions. Thanks!

![image](https://github.com/novacode-nl/odoo-formio/assets/328803/23b747c5-2a55-47f1-a3ef-2ed545a97cb8)

**Comment by deeroen** [comment]
Hello,

I am also using the URL filestore, but somehow the Qweb report does not print the images, only the report.

May I ask you how can I troubleshoot it?

Kind regards,

Jérôme
