### ISSUE TITLE
Form doesnt render properly - V17

### ISSUE THREAD

**Issue by nmoturi** [novacode-nl/odoo-formio#285]
The form doesn't seem to be rendered properly - tried with Google chrome & firefox. Form builder design is fine without any issues

![image](https://github.com/user-attachments/assets/be8229bf-b4dd-4a64-b530-6ab2c2ef9e46)

Thanks,
Naran

**Comment by bobslee** [comment]
@nmoturi where does the form issue occur ?
Odoo backend, portal, website or embedded ?

**Comment by nmoturi** [comment]
Hi Bob,

The form issue is in the Odoo backend.

Thanks,
Naran

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bobslee** [comment]
@nmoturi strange thing is, this doesn't occur on the Odoo v17 systems I know.

Can you test and respond whether it occurs on the demo v17 instance ?
https://demo17.novaforms.app/

Login
- User: demo
- Password: demo

**Comment by bobslee** [comment]
@nmoturi Friendly reminder. 
Can you test on the demo environment?

Otherwise you can request our support (eg video call) by submitting the contact form:
https://www.novaforms.app/contact

**Comment by nmoturi** [comment]
Thanks, Bob for the response.

I’ve tested on your demo server and it seems to be good, I cannot replicate the same issue. We are seeing the below JS warnings however don’t see anything similar on your demo site.

***@***.***

Thanks,
Naran
From: Bob Leers ***@***.***>
Date: Friday, 16 August 2024 at 10:45 PM
To: novacode-nl/odoo-formio ***@***.***>
Cc: Naran M ***@***.***>, Mention ***@***.***>
Subject: Re: [novacode-nl/odoo-formio] Form doesnt render properly - V17 (Issue #285)

@nmoturi<https://github.com/nmoturi> Friendly reminder.
Can you test on the demo environment?

Otherwise you can request our support (eg video call) by submitting the contact form:
https://www.novaforms.app/contact

**Comment by bobslee** [comment]
@nmoturi I expect it's a strange issue on your side.

If you need my support to analyse and solve, you can submit the contact form to discuss:
https://www.novaforms.app/contact

I will close the issue now.

**Comment by chjud** [comment]
Check if the entry "bootstrap 4.4.1 bootstrap.min.css" type "CSS" Attachment Type "URL" exists in Forms > Configuration > Installed Formio Versions > "your version" > Assets

For some reason i experienced also quite strange behaviour on the existence of the entry. Sometimes is was missing from the beginning, but then added if I installed an older version. Sometimes an update would add teh entry, sometimes it wouldn't. Just add it manually, solves the problem
