### ISSUE TITLE
formio v16 : error when submit a form

### ISSUE THREAD

**Issue by mslokhat** [novacode-nl/odoo-formio#287]
Hello
when submitting a simple form in odoo 16 

2 fields : name 
email

  File "/opt/odoo16/odoo-custom-addons/formio/models/formio_form.py", line 233, in _after_write
    rec._process_api_components()
  File "/opt/odoo16/odoo-custom-addons/formio/models/formio_form.py", line 248, in _process_api_components
    if self.submission_data.get(self.builder_id.component_partner_email):
AttributeError: 'str' object has no attribute 'get'

Thanks

**Comment by bobslee** [comment]
@mslokhat Thanks for reporting.
I will check upcoming days and let you know when there's a fix.

**Comment by bobslee** [comment]
@mslokhat Fix has been pushed and released.
Also mind the deprecation warning. This feature will be deprecated in Odoo v18.

Please close this issue when it has been solved.
