### ISSUE TITLE
 File Upload to S3 Storage Failing

### ISSUE THREAD

**Issue by Q-Niranjan** [novacode-nl/odoo-formio#288]
1. I created an Odoo module and integrated it with odoo-formio. When selecting the URL storage type and writing the controller accordingly, it works fine.

2.However, when selecting S3 storage, it directly hits the endpoint /storage/s3, and I receive the following error:
`{werkzeug: 127.0.0.1 - - [12/Sep/2024 11:15:38] "POST /storage/s3 HTTP/1.1" 500 - 5 0.003 0.021}
`

3. When trying to retrieve the file, I encounter a "file not found" error. The JSON data provided is as follows:
`{
  "name": "cert-94f26a94-2fee-46cf-b376-1c9cfdc99cec.pdf",
  "size": 31292,
  "type": "application/pdf",
  "groupPermissions": null,
  "groupId": null,
  "multipart": false
}
`
4.The issue seems to be related to uploading this JSON formatted data to an S3 bucket.
Details Needed:
How can I successfully upload the actual file on S3 bucket?
Any help or guidance would be greatly appreciated. Thank you!

**Comment by bobslee** [comment]
> How can I successfully upload the actual file on S3 bucket?

I don't know. Never tried to implement different storage providers, except the URL - done in module **formio_storage_filestore**.
https://github.com/novacode-nl/odoo-formio/tree/17.0/formio_storage_filestore

> How can I resolve the TypeError: 'Logger' object is not callable issue?

That error seems not related to your code snippet. Any idea where that code is ?

For which Odoo version are you developing this?

**Comment by Q-Niranjan** [comment]
odoo17

**Comment by bobslee** [comment]
Sorry, I can't assist with this for free.
I want my support you can submit the contact form https://www.novaforms.app/contact , so we can discuss.

**Comment by bobslee** [comment]
@Q-Niranjan we received your contact form submission. 
But when we reply, we receive an error your email address doesn't exist.

**Comment by Q-Niranjan** [comment]
> @Q-Niranjan we received your contact form submission. But when we reply, we receive an error your email address doesn't exist.

nkb355093@gmail.com
