### ISSUE TITLE
error install website_formio @api.multi

### ISSUE THREAD

**Issue by thomaspot** [novacode-nl/odoo-formio#34]
When installing V13 you get an error 
@api.multi

https://github.com/novacode-nl/odoo-formio/blob/13.0/website_formio/models/formio_builder.py#L20

**Comment by bobslee** [comment]
Has been fixed in https://github.com/novacode-nl/odoo-formio/commit/cf1a2e6155924f1ecd2da112dbfde06cf398d9c7#diff-93817eed631614f1e035187bab57f830L20

Please let me know or close this issue.

**Comment by bobslee** [comment]
Solved.
No answer from reporter. In case the issue still persists, you could re-open.
