### ISSUE TITLE
Height of iframe formio.portal_my_formio

### ISSUE THREAD

**Issue by thomaspot** [novacode-nl/odoo-formio#35]
using a iframe the height of the frame is too small to display correct.
Qweb
formio.portal_my_formio_edit
If I set a height it is OK.
<iframe t-attf-src="/formio/form/#{form.uuid}/root" class="formio_form_embed"/>
replacing by 
<iframe t-attf-src="/formio/form/#{form.uuid}/root" class="formio_form_embed" style="height:600px;"/>
Made it better and readable, but would be better to set a dynamic height?

**Comment by bobslee** [comment]
Hi @thomaspot, height sizing should already be handled by CSS media-queries. But when I implemented this, I wasn't sure about all cases (screen resolutions).

Please could you report your screen resolution? So I'm able to reproduce the issue.

**Comment by bobslee** [comment]
Indeed.. you're right @thomaspot!
I now can reproduce this issue and it seems I solved it. Still testing and improving further.

Seems to be a jQuery DOM loading issue. When in mode debug=assets the issue didn't appear.
(So my previous answer wasn't thoroughly tested).

**Comment by bobslee** [comment]
Should now be fixed for Odoo 11, 12 and 13. 

@thomaspot Please:
- Re-download and upgrade the `formio` module (version `3.1`).
- Let me know whether the issue has been solved

**Comment by bobslee** [comment]
No answer from report. In case the issues still persists, you could re-open.
