### ISSUE TITLE
Drag and drop builder not appearing on UI

### ISSUE THREAD

**Issue by jl-costa** [novacode-nl/odoo-formio#4]
Environment: Odoo open source 11.x, running on Ubuntu 16.04

After setting up the the module, the drag and drop builder doesn't show any options for editing or adding fields to the form:

![image](https://user-images.githubusercontent.com/26030520/52567483-328a4e00-2deb-11e9-8ddc-2f85ba6748f5.png)

**Comment by bobslee** [comment]
Maybe your issue is subjected to my reported issue #3
Could you check and answer the outcome please?

Otherwise, please check and report:
- Any clues in the Odoo server log?
- webbrowser developer mode (JavaScript error)

**Comment by bobslee** [comment]
@jl-costa could you please provide me more info?
Or close your issue?
