### ISSUE TITLE
Public access to form

### ISSUE THREAD

**Issue by onmywaytoheaven** [novacode-nl/odoo-formio#5]
Hi! Is it possible to make form visible to public i.e w/o login on website? I tried to change 'auth' property in controller and add public odoo user to Formio User group but it didnt help much. 
Based on the python exception 
```
Error to render compiling AST
AccessError: ('You cant get access to this document.', None)
Template: formio.formio_html_head
Path: /templates/t/head/t[1]/link
Node: <link rel="stylesheet" type="text/css" t-att-href="css.url"/>
```
I guess that happened because of using "ir.attachment" in formio versioning assets.

**Comment by bobslee** [comment]
Hi, thanks for your interest!
I have to check whether that would be possible and easy to implement (currently I'm into a lack of time).

Would be ok to just serve the form on a standalone page outside the Odoo web portal? The same form page like it's in the backend (behind login).
 Because the rendering of a Formio form as a snippet/widget on an Odoo web page world take too much development effort for now.

Let me know your thoughts.

**Comment by onmywaytoheaven** [comment]
Hi! Thank you for answer!
Do you mean use PaaS solution such as https://www.form.io/ for public form for now?

**Comment by bobslee** [comment]
No, that's not what I proposed.
Maybe I'm able to implement your request (in a simple approach) the upcoming days, into the Form.io module.

Keep you posted.

**Comment by bobslee** [comment]
Hi @onmywaytoheaven,
Unfortunately your request isn't straightforward to implement and it takes some effort to develop.
Of course this would be a nice feature, but in short term I don't have any opportunity to work on this.

Feel free to submit a PR if possible :)
I suggest this would go into a separate module, named e.g. `website_formio`.

A question I already have regarding access control of the forms:
- Any public user (without login) is allowed to view, fill-in and submit forms?
- Only portal users are allowed to view, fill-in and submit forms?

Hereby this issue remains open for a while, until you decide to leave or close it.

Kind regards,
Bob

**Comment by bobslee** [comment]
Just implement the assignment and usage of forms by Portal Users.

Still need to document this on the app / module page.

**Functionality:**
- On the **form builder** (`formio.builder`) enable the checkbox **Portal usage**.
- Assign a **form** (`formio.form`) to a Portal User
- The assigned form(s) are listed on the **My account** page.
- Portal User can open and submit the assigned forms.

**Comment by bobslee** [comment]
Hi @onmywaytoheaven 

Please could you let me know whether this functionality does work for you?
Also I hope you could share ideas or issues :)

Greets,
Bob

**Comment by bobslee** [comment]
**News regarding public forms - for Portal users:**

Last days I implemented several *new features*:
- Forms assignment and usage (also creation) for Odoo *Portal users*.
- Possbility to restrict forms to assigned forms (Portal User, Internal User).
- Translation system for Form labels, placeholders etc (Dutch translations for now).
- Language selector on Form, which loads the translated form.
- Simple form wizards.
- Form state (Pending, Draft, Completed, Canceled). Once Completed or Canceld, the form can't be modified anymore - is readonly.
- Form invitation mail.

I hope you enjoy the featuers and this ticket can be closed now.

**There's a DEMO environment available from now:**

https://odoo12-b4a887d572e9.victhorious.com/web/login

*Users (Email / Password):*
- demo / demo
- portal / portal

**Comment by onmywaytoheaven** [comment]
Wow! It is very good! Now this is a great tool! Thank you!

**Comment by bobslee** [comment]
Thanks for reviewing!
By the way.. I fixed the wizard form feature.
