### ISSUE TITLE
It is not possible to save a form component when the name component is in cyrillic

### ISSUE THREAD

**Issue by onmywaytoheaven** [novacode-nl/odoo-formio#6]
Hello!
Its not possible to save form component when the name of component have cyrillic letters.
Steps to reproduce:
1) Open form builder
![изображение](https://user-images.githubusercontent.com/43062804/64251227-a96e6c00-cf20-11e9-8fec-808082b6c568.png)
2) Drag and drop form component
3) Change label to cyrillic 
![изображение](https://user-images.githubusercontent.com/43062804/64251323-fc482380-cf20-11e9-8e2e-fbcbc69e0e48.png)
4) Press save
**expected behaviour** - form saved and closed
**what i get** - nothing happend
![formio_bug](https://user-images.githubusercontent.com/43062804/64251664-b0e24500-cf21-11e9-931b-cdf37e75358e.gif)

This happend even if label name consist of mix with latin and cyrillic letters

I can save form component with latin label and change label name after that - this is allowed

Browser: Firefox 68.0.2
Tested on your env https://odoo12-b4a887d572e9.victhorious.com

**Comment by bobslee** [comment]
Affirmative :)
I'm able to reproduce this issue as well.

However, the cause lies in the **Form.io JS library**.
Same issue on https://formio.github.io/formio.js/app/builder

Please could you report this issue in the project: https://github.com/formio/formio.js

Thanks in advance!

**Comment by bobslee** [comment]
Closed here, because this issue lies in the Form.io (JS / core) project.
