### ISSUE TITLE
[odoo13] formio public form: expiration date isn't working

### ISSUE THREAD

**Issue by lieblinger** [novacode-nl/odoo-formio#61]
Public form is ignoring the "Expire After" field. Form is always fillable, also after official expiration date.

Expected behaviour: After expire date reached, form shouldn't accessible anymore.

**Comment by bobslee** [comment]
Ok, I shall investigate this further. Worked a while ago for Form server from /formio/public/... URL. 

However I already stumbled on a subtle bug in the formio.form get_form() function. 
The search query shouldn't obtain public forms. Shall fix this a.s.a.p.

**Comment by bobslee** [comment]
Hi @lieblinger, I just tested and works here.
Please re-open the issue if the problem still persists, and specify which Odoo and Forms module version.

See the screenshot below for my test with some notes.

Tested with:
- Odoo 14.0
- Forms (formio) module version: 8.10

![image](https://user-images.githubusercontent.com/328803/104810330-14f26a00-57f4-11eb-9d07-56bb26ca54ff.png)
