### ISSUE TITLE
when support odoo 14

### ISSUE THREAD

**Issue by ericdai** [novacode-nl/odoo-formio#64]
I want to know when get odoo 14 porting？

**Comment by bobslee** [comment]
In case you could port it, I would be glad to receive a pull request.
Otherwise it depends on the need of my existing customers.
In case you would like me to port the module(s), send me a DM mail: bob (at) novacode (dot) nl

**Comment by bobslee** [comment]
@ericdai I just released the Odoo Forms (Formio) modules for version 14.
