### ISSUE TITLE
Odoo 12 Add Form to Website

### ISSUE THREAD

**Issue by framatt** [novacode-nl/odoo-formio#65]
Odoo 12 does not seem to have the ability to add the snippet. How do you add the form to a webpage?

**Comment by bobslee** [comment]
Hi @framatt, Currently the formio_website snippet isn't backported to v12.
I'm awaiting on a PR from somebody, who maybe backported it to v11.
Feel free to contribute, develop a PR :-)

**Comment by framatt** [comment]
I was able to make it work by editing the html (Customize->HTML/CSS Editor) and adding this

<div class="formio_form_iframe_container">
        <iframe class="formio_form_embed" id="iFrameResizer0" scrolling="no" style="overflow: hidden; height: 386px;" submission="defaultData" src="/formio/public/form/create/c2c86d69-9534-47e4-a214-0a2e2faa7687"/>
        <script class="o_default_snippet_text">
                        iFrameResize({}, '.formio_form_embed');
                    </script>
      </div>

**Comment by bobslee** [comment]
@framatt Indeed, I know.. that's a nice workaround.
But the draggable website snippet like in v13 (addon: website_formio) still won't work, due to API incompatibility... probably JavaScript.
