### ISSUE TITLE
When using version 4.12.1 of formio.js, the form-builder cannot be saved.

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#66]
When using version 4.12.1 of formio.js, the form-builder cannot be saved.

**Comment by niulinlnc** [comment]
Find steps to save normally:
When using formio. Js with version 4.12.1, you need to check the wizard. When adding fields on each page, you need to edit the page before exiting, and click save again.

**Comment by bobslee** [comment]
@niulinlnc Affirmative, few days ago I also experienced this with `4.12.1-rc-28`.
I shall analyse and solve, if I'm available/free. Shall comment here.

**Comment by bobslee** [comment]
@niulinlnc issue has been fixed.
Which seemed to work until this/current Form.js release (quite a scary bug in this module).

I also encounter a different bug...
Sometimes the Form Builder (canvas/body) is empty, one needs to refresh the webbrowser. 
I checked/analysed the JS console, but still no clue.. Some promises errors, but those also occur with a clean Odoo install and only the Sales module.
I shall submit a new issue for this one.

**Comment by niulinlnc** [comment]
This works in a single page state, and if wizards are added, the schema data will lost. @bobslee

**Comment by bobslee** [comment]
@niulinlnc So if I understand correctly, the issue still occurs, only with a **wizard** Form Builder?

**Comment by niulinlnc** [comment]
@bobslee Yes, with the page wizard enabled, if you create a new page, it will result in loss of schema data when it returns.

**Comment by bobslee** [comment]
@niulinlnc thanks for catching up again.
I created a new issue regarding the Formio Builder wizard #71
