### ISSUE TITLE
Form Builder canvas/body empty (refresh browser as silly workaround)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-formio#69]
Since working with newer Form.js (library) versions... `4.12.1`

Sometimes the Form Builder (canvas/body) is empty, one needs to refresh the webbrowser.
I checked/analysed the JS console, but still no clue.. Some promises errors, but those also occur with a clean Odoo install and with e.g. only the Sales module installed.

![image](https://user-images.githubusercontent.com/328803/99685073-77dcb480-2a82-11eb-9471-45e481416635.png)

**Comment by niulinlnc** [comment]
This situation did not happen here, only formio.js(version >=5.0) will have this situation.

**Comment by bobslee** [comment]
@niulinlnc Are you really sure about that?
Which webbrowser did you used with Form Builder >=4.12 ?

**Comment by niulinlnc** [comment]
@bobslee yes, 4.12.1 and 4.12.2.rc.1 are both normal.

**Comment by niulinlnc** [comment]
use google chrome.

**Comment by bobslee** [comment]
@niulinlnc this issue is also fixed by my latest commit...
https://github.com/novacode-nl/odoo-formio/commit/7d9674a2d5c542421676149b32aaebd673fdb1d3#diff-ab6986dd0fd3af3bdb47f4c6a9543fa7102ef876912808f0b6617fb941b0b4d4R34

A big win, because latest Formio releases/versions seem to work now! `>=4.12.1`, `>=5.0.0-m.x`

From now on a Formio Builder object shall be instantied (contructor).
Seems they extended the highlevel AP, also metnoined e.g. https://github.com/formio/formio.js/issues/762#issuecomment-562892095
