### ISSUE TITLE
Problem with Edit Grid Component

### ISSUE THREAD

**Issue by onmywaytoheaven** [novacode-nl/odoo-formio#7]
Hello!
There is a problem with Edit Grid component
It does not close when you click on the “Cancel” button in the modal view
![formio_bug2](https://user-images.githubusercontent.com/43062804/64258468-fdcd1800-cf2f-11e9-9c34-e07a21d121af.gif)

**Comment by bobslee** [comment]
Thanks for reviewing and sharing your issues @onmywaytoheaven !

However I can't reproduce this issue.
Please could you check the Firefox developer toolbar (Console) for any errors.

Browser (also): Firefox 68.0.2

**Comment by onmywaytoheaven** [comment]
When i first time click "Cancel" button nothing happened in console.
When i click it second time thereis JS TypeError
`TypeError: t is undefined formio.full.min.js:152:119394
    value https://unpkg.com/formiojs@latest/dist/formio.full.min.js:152
    value self-hosted:1047
`
Same in Microsoft Edge - cant close by clicking "Cancel" (gif attached)
![formio_cancel_bug gif](https://user-images.githubusercontent.com/43062804/64280178-48af5580-cf59-11e9-9939-788b31b3c611.gif)

**Comment by bobslee** [comment]
Please could you test and reproduce this with official Form.io Demo? - https://formio.github.io/formio.js/app/builder

In case the error occurs, please create an issue on https://github.com/formio/formio.js

**Comment by bobslee** [comment]
Closed here, because this issue lies in the Form.io (JS / core) project.
