### ISSUE TITLE
[formio] Builder: wizard issue, cannot be saved (>= 4.12.1)

### ISSUE THREAD

**Issue by bobslee** [novacode-nl/odoo-formio#71]
Using the Formio Builder **wizard** with version 4.12.1:
When adding fields on each page, you need to edit the page before exiting, and click save again.

If you create a new page, it will result in loss of schema data when it returns.

Issue orignally mentoined in #66

**Comment by niulinlnc** [comment]
The official [example](https://formio.github.io/formio.js/app/builder) is handled very well. The as JSON Schema on the right can update the data in real time. I don't know if this can be used for reference.

**Comment by bobslee** [comment]
Just tested and seems no issue anymore.
- Odoo Forms (formio) module version: 8.10
- Formio.js version: 5.0.0-m.10

I frequently updated the field `Wizard` in the Form Builder, which toggles the Form (Builder) either in Wizard mode or with pages in a panels component. (see screenshot).

![image](https://user-images.githubusercontent.com/328803/104809296-8fb78700-57ec-11eb-934f-0cf293891737.png)
