### ISSUE TITLE
Visitors cannot jump to the specified public webpage after submitting the form through the public form-builder

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#75]
As a normal visitor (no odoo user or portal user), but after he filled out the form, the page turned into a new form, and did not jump to the specified page.

**Comment by bobslee** [comment]
@niulinlnc yep I understand. 
That functionality (redirect) only works when the Form has been embedded in `<iframe/>`, which is most of the use cases I'm involved in.

Below some notes about this now works, via the webbrower postMessage API...
(which was rather tricky to implement)
- The Form emits an event/message to it's `<iframe/`> parent window => https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/static/src/js/form/public_create_app.js#L45
- Parent window handles the event to redirect => https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/static/src/js/formio_form_container.js#L10

In case you need a redirect in the Form window, there's some development work needed.

**Comment by bobslee** [comment]
@niulinlnc some questions for clarification:

Is the Form loaded into an Odoo website page (from the Forms snippet) ?
Or do you use the public Form its endpoint URL `/formio/public/form/<string:uuid>/root` ?

**Comment by bobslee** [comment]
Please could you answer my latest question, to I can analyse/solve this.
CC: @niulinlnc @banqu @ongood

**Comment by niulinlnc** [comment]
@bobslee Uses public, not loaded into Odoo web page.

**Comment by bobslee** [comment]
@niulinlnc which URL is used in public?
(implemented with routes below)

`/formio/public/form/create/<string:builder_uuid>`
https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/controllers/public.py#L92

`/formio/public/form/<string:uuid>`
https://github.com/novacode-nl/odoo-formio/blob/14.0/formio/controllers/public.py#L23

**Comment by niulinlnc** [comment]
@bobslee Is /formio/public/form/create/<string:builder_uuid>
