### ISSUE TITLE
The form generated by the public form builder, which is not public by default

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#76]
As the title.

**Comment by bobslee** [comment]
@niulinlnc please provide more info (steps, maybe screenshots?)

**Comment by niulinlnc** [comment]
![`(ZP0 D3U(HYXUGU3 OABZN](https://user-images.githubusercontent.com/11767049/99899961-f4bc9800-2ce7-11eb-957c-b9cd605ff7b7.png)
![%{P}XVJBB)RCKCV2NDCK$C0](https://user-images.githubusercontent.com/11767049/99899966-fede9680-2ce7-11eb-841e-3fba5b26d190.png)

**Comment by bobslee** [comment]
@niulinlnc I understand your question.
Please close this, when my explanation (below) clarifies and the functionality works like expected.

The field **`Public Access`** is realtime computed, based on the **`Expire After`** interval, configured in the Form Builder.
So check and configure the field **`Expire After`** in the Form Builder.

See the screenshot which shows how it basically works.

P.S. I also added the field **`Public`** in the Form Builder its list-view. This field just shows whether the Forms was initially setup (by Builder) for Public Access.

![image](https://user-images.githubusercontent.com/328803/104810547-9991b800-57f5-11eb-9ce6-75c03869f169.png)
