### ISSUE TITLE
Can it support pdf form？

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#81]

**Comment by bobslee** [comment]
Do you mean printing the Form (submission) to PDF file?

**Comment by niulinlnc** [comment]
@bobslee No, It is based on a pdf file to fill in the content, Look at this official example:
https://formio.github.io/formio.js/app/builder
![无标题](https://user-images.githubusercontent.com/11767049/99937514-e1213800-2da0-11eb-8976-423ffc105995.jpg)

**Comment by niulinlnc** [comment]
I tried the form in pdf format, but I could not upload the pdf file.
![无标题2](https://user-images.githubusercontent.com/11767049/99937915-baafcc80-2da1-11eb-8150-e491f3de5999.jpg)

**Comment by bobslee** [comment]
@niulinlnc That's a nice feature indeed. I never tried.

Regarding the "Unauthorized" error... Did you checked: 
- WebDev tools (console, network) ?
- Odoo log file?

Keep me posted about this please.

**Comment by niulinlnc** [comment]
![无标题5](https://user-images.githubusercontent.com/11767049/99940681-a40c7400-2da7-11eb-93cb-7da4f5ebb2a4.jpg)

**Comment by niulinlnc** [comment]
@bobslee There is no abnormal information in odoo.log. And the exception is displayed on the WebDev tool as shown above.

**Comment by bobslee** [comment]
@niulinlnc You see, it tries a POST to the Formio (SAAS platform) API, which raises the error.
Yet I don't know why the Formio API is required for the PDF Form.

For me it's no prio to research and implement. If you would like to work on this, would be great!
Let me know your decision or can you close this issue?

Thanks for the info!

**Comment by niulinlnc** [comment]
@bobslee I used the latest 4.12.2.rc.3 and 5.0.0-m.10 for testing. There was a progress bar when uploading, and the file was uploaded successfully. After uploading, it prompts that there is no authorization. Is this only available on the official saas platform? I found that there is another way to display pdf: by

Set up
"settings": {
     "pdf": {
       "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
     }
   },
![无标题6](https://user-images.githubusercontent.com/11767049/99946432-4c730600-2db1-11eb-868a-db74e43a99fe.jpg)
![无标题7](https://user-images.githubusercontent.com/11767049/99946437-509f2380-2db1-11eb-9504-9ba8e4c5c503.jpg)

**Comment by bobslee** [comment]
@niulinlnc I don't know... I assume it's only supported on the official SAAS platform.
Apparently some open-sourced libraries/APIs also contain SAAS features.. like we see in the Form Builder tools.

Maybe you could investigate further or close this issue?

**Comment by niulinlnc** [comment]
@bobslee I  have a general idea of the solution to this problem：
- The first way is to upload PDF file by registering APi.form. IO account, which is not good ideal and use will be limited.
- The second option is to upload the PDF file to Odoo server, but need use the pdf2htmlEX plug-in to render the PDF file as HTML in the form-builder. This will allow you to edit the PDF file. Strangely, the PDF2HTML example I downloaded from PDF2HTML was not able to add fields to it. Maybe the parameters are different.
(https://github.com/pdf2htmlEX/pdf2htmlEX)
How to use PDF2HTML and set the correct parameters. It's too difficult for me.
![无标题](https://user-images.githubusercontent.com/11767049/100040997-57767680-2e43-11eb-8083-cc93ad4e6acd.png)

**Comment by niulinlnc** [comment]
I imagine that when I uploaded the PDF file here, the PDF file was automatically converted to.HTML, and then the API appended formio-pdf.js to the HTML file, and in .html ：
<div id="page-container">
....
....
<div id="pdf-form"></div>(add)
</div>
It add:
<div id="pdf-form"></div>
so that it can be edited.
![无标题](https://user-images.githubusercontent.com/11767049/100047905-8b0ace00-2e4e-11eb-8eb3-45c579afc4ee.png)

**Comment by bobslee** [comment]
@niulinlnc is an assumption or you already experienced?

By the way.. the uploaded image didn't succeeded here?

**Comment by arezkielias** [comment]
@niulinlnc 
Could you please tell me how you were able to use Solution #2, which is uploading the PDF directly to Odoo then converting it to HTML.
Your help is much appreciated.
