### ISSUE TITLE
Module needs a better icon

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#86]
The original icon does not match the official style, and an icon consistent with the official style is required.

**Comment by niulinlnc** [comment]
I personally designed a few icons，the color can be adjusted arbitrarily before confirming.
![icon1](https://user-images.githubusercontent.com/11767049/100177646-73464f00-2f0d-11eb-9be8-5aacb9d23650.png)

**Comment by niulinlnc** [comment]
![icon2](https://user-images.githubusercontent.com/11767049/100177890-dfc14e00-2f0d-11eb-86c1-eaff778b438d.png)

**Comment by niulinlnc** [comment]
![icon3](https://user-images.githubusercontent.com/11767049/100178054-28790700-2f0e-11eb-8e44-02383af217c5.png)

**Comment by niulinlnc** [comment]
![icon4](https://user-images.githubusercontent.com/11767049/100181514-66c5f480-2f15-11eb-8a10-045d5594ec79.png)

**Comment by niulinlnc** [comment]
![icon](https://user-images.githubusercontent.com/11767049/100190446-38521480-2f29-11eb-97a4-daa744fdca35.png)

**Comment by bobslee** [comment]
@niulinlnc Thanks for the improvement proposals! Really appreciated!
I like your designs.

My remarks, requests:
- Background color is nice.
- Keep it really simple.
- Just leave the "textual" formio  out. Just an icon/drawing.
- Could you please design according similar idea from the image below? To get that "drag and drop" feel... 
(don't copy from image below).
- Maybe, if there's any room left.. you could add the curly braces **`{ }`**

![image](https://user-images.githubusercontent.com/328803/100204729-8274cf00-2f04-11eb-99b1-8d57126201af.png)

**Comment by bobslee** [comment]
@niulinlnc please could you also design proposal(s) for the banner/cover image?
https://github.com/novacode-nl/odoo-formio/blob/13.0/formio/static/description/banner.png

It's shown in the Odoo Apps Store...
![image](https://user-images.githubusercontent.com/328803/100205573-966d0080-2f05-11eb-8573-002629d69964.png)

**Comment by niulinlnc** [comment]
@bobslee 
![icon6](https://user-images.githubusercontent.com/11767049/100227987-f9d64d00-2f5c-11eb-9b9b-65f8f9e83394.png)

![icon7](https://user-images.githubusercontent.com/11767049/100228093-1d00fc80-2f5d-11eb-98d2-058b03009c7d.png)

![icon8](https://user-images.githubusercontent.com/11767049/100228118-2722fb00-2f5d-11eb-87b1-010379ec0bd7.png)

**Comment by bobslee** [comment]
@niulinlnc the last one is awesome!
https://user-images.githubusercontent.com/11767049/100234280-d19f1c00-2f65-11eb-898c-7ea96ff1f8bd.png

Please could you also propose a new banner/cover image?

**Comment by bobslee** [comment]
Tile in banner image without ".io"
which refers to a domain TLD...
assuming a web service integration, which this module isn't  ;)

So basically:
**Formio**

**Comment by niulinlnc** [comment]
@bobslee Designing banners requires photoshop. I will ask my colleague to help design some banners tomorrow. She is a professional.

**Comment by bobslee** [comment]
@niulinlnc Thanks, really kind from you!
Let's evolve these modules stack to pro, beyond awesome!

**Comment by niulinlnc** [comment]
@bobslee The icon design is done by coreldraw8 software. The material uses vector graphics, which is my first in the industry and an innovative and rapid design method. Compared with using photoshop to make icons, it saves several times of time.

**Comment by bobslee** [comment]
@niulinlnc thanks for sharing.
I really like the idea of vector graphics, also rendered by software e.g. for graphs.
I'm not a graphic desinger tough, so any free help like yours (colleague, contributors) is appreciated.

**Comment by niulinlnc** [comment]
You are right, we need to remove all formio and form.io asap, otherwise we will now advertise for formio for free.

**Comment by bobslee** [comment]
Until Odoo version 13, we shouldn't rename any technical occurrences of `formio`. 
This shall cause regression, breakage.. also with custom development. 

Porting these modules to v.14 would be possible to rename. 
However, I like some technical prefix in case Odoo or others come up with Forms modules ;)

**Comment by niulinlnc** [comment]
![模块1](https://user-images.githubusercontent.com/11767049/100324784-ab7b8980-3002-11eb-88bc-a2a6396e4eef.gif)

**Comment by bobslee** [comment]
@niulinlnc why the change? I really liked the green-ish highlighting.

Thanks for the design! Realy nice work!

**Please could you process some requests below?**
Also shown on my silly crafted image below. I annotated on your 1st version.

**(1) Rename title: Forms Builder**
Also with "Builder" in different color (e.g. grey)

**(2) Remove the `V13` (top right)**
This banner shall be needed for other versions too.

**(3) Replace "Odoo"**
Prefer: https://odoocdn.com/openerp_website/static/src/img/assets/svg/odoo_logo.svg
For more brand assets see: https://www.odoo.com/nl_NL/page/brand-assets

**(4) Minor change in description**.
Build professional, easy-to-use and versatile forms to collect any information you need for your business.

**(?) Some thoughts about keywords**
Is it possible to add some keywords (or animate these with the description) ?
**keywords**: _Powerful Form Builder, Forms & business process integrations, Multilingual, Developer Friendly, on-premise_

![image](https://user-images.githubusercontent.com/328803/100368096-702d8a80-3003-11eb-9225-9192d8345bff.png)

**Comment by niulinlnc** [comment]
@bobslee The banner image has been adjusted.

**Comment by bobslee** [comment]
@niulinlnc thanks for the change!
I've some requests again. Hope I don't bother you too much ;)

There's too much movement (and speed) in the animation.
Maybe we just could stick with my following proposal? Thanks!

![image](https://user-images.githubusercontent.com/328803/100431503-8cc7d200-3098-11eb-9320-d72199d14634.png)

**Comment by niulinlnc** [comment]
![3](https://user-images.githubusercontent.com/11767049/100448010-93803480-30ec-11eb-86ed-6ab06c292b53.gif)

**Comment by bobslee** [comment]
@niulinlnc I think we're almost completed. Thanks!

1. Change "Builder" (in title) green color. It doesn't come out (less contrast). Maybe to (former) dark blue or grey-ish again?
2. Move/place text "Powerful form builder..." only in the light-blue area. Is possible?
3. Fix typo: `information to need` => `information you need`

**Comment by niulinlnc** [comment]
![4](https://user-images.githubusercontent.com/11767049/100454556-18bd1680-30f8-11eb-98dc-4710250b4bca.gif)

**Comment by bobslee** [comment]
@niulinlnc that just looks awesome!

One last thingee...
Would be possible to make the **green in the icon, a bit lighter**? - like the green of "Builder" ?

**Comment by niulinlnc** [comment]
![5](https://user-images.githubusercontent.com/11767049/100461319-9b979e80-3103-11eb-9eb4-bf6b0e17b9c5.gif)

**Comment by bobslee** [comment]
@niulinlnc Nice, well done!
I would like to import these into this project its modules? 

Any objections? No legal concerns or whatsoever?

**Comment by bobslee** [comment]
@niulinlnc By the way...

It would be great if we'd get a second banner image, for the additional modules.
So we'll keep this one for the main/base `formio` module :D

IMHO the banner for additional modules should contain at least following.
Still need to ponder about a description, whether or not....

![image](https://user-images.githubusercontent.com/328803/100462677-e6e18b00-30ca-11eb-8eef-d4940a97943f.png)

**Comment by niulinlnc** [comment]
> @niulinlnc Nice, well done!
> I would like to import these into this project its modules?
> 
> Any objections? No legal concerns or whatsoever?

The picture designs are all original without any legal risks.

**Comment by bobslee** [comment]
@niulinlnc Still one request for the `formio` main image..

Text below "Powerful form builder" should be lighter or less bold. Please :)

Addressing image in comment: https://github.com/novacode-nl/odoo-formio/issues/86#issuecomment-734872953

**Comment by niulinlnc** [comment]
@bobslee I did not understand the second suggestion.

**Comment by bobslee** [comment]
@niulinlnc Please could you change the font (style) of the description according to the image on the left?
So only the font/style of the description starting with: `Easy-to-use, professional...`.

![image](https://user-images.githubusercontent.com/328803/100538375-b109e700-322f-11eb-9ac6-32614bba3b5c.png)

**Comment by niulinlnc** [comment]
![7](https://user-images.githubusercontent.com/11767049/100540631-61500d80-3279-11eb-85e6-91fbdad6eb5b.gif)

**Comment by bobslee** [comment]
@niulinlnc It would be really professional if there's a second (extra) banner for all the extra Forms modules.
We need to distinguish the banners of the main app `formio` and the extra modules.

Some suggestions for the **extra banner**, to distinguish from the banner of the main `formio` module:

**Colors:**
Background dark-blue and beam light-blue.

**Title:** 
Forms Integration (word "Integration" should be dimmed, like "Builder" in main app banner)

**Description:**
Powerfull Forms Integration
Easy-to-use, professional and versatile forms to integrate and collect any information you need for your business.

**Comment by niulinlnc** [comment]
![Integration](https://user-images.githubusercontent.com/11767049/100540945-98272300-327b-11eb-9d36-fcca59acd854.gif)

**Comment by bobslee** [comment]
@niulinlnc Thanks! I need to think about this design, for the extra banner.
Let you know a.s.a.p.

**Comment by bobslee** [comment]
@niulinlnc 2 requests below:

**(1) Extra banner**
Regarding the title `Integration`...
Are you sure it's the same color as the beam? Could be slightly lighter?

**(2) Both banners**
Please _capitalize_ the `Forms` word in text..

`Easy-to-use, professional and versatile Forms to integrate and collect any information you need for your business.`

**Comment by niulinlnc** [comment]
![Integration2](https://user-images.githubusercontent.com/11767049/100542344-4a62e880-3284-11eb-994c-54b84e284247.gif)

**Comment by bobslee** [comment]
@niulinlnc Please capitalize the word `Forms` in the main app banner too :)

**Comment by niulinlnc** [comment]
![8](https://user-images.githubusercontent.com/11767049/100546276-7a69b600-329b-11eb-8631-73d93bc81c01.gif)

**Comment by bobslee** [comment]
@niulinlnc I shall publish the images (icon, banner) upcoming days. 
Also with the renaming (PR) of module title, menu, labels.

(At least for version 13, maybe 12 and 11)

Please keep me posted if you've any improvements or questions.

**Comment by bobslee** [comment]
@niulinlnc Little mistake in description text for both banners (my fault).

Please start with:
`Build easy-to-use ...`

Keep it nicely aligned and font style like latest design.

**Comment by bobslee** [comment]
@niulinlnc Please could you send me your email-address?
Would like to invite you on Slack.

My email: `bob (at) novacode (dot) nl`

**Comment by niulinlnc** [comment]
![builder1](https://user-images.githubusercontent.com/11767049/100610942-84e38880-334b-11eb-923e-93f9d3f82532.gif)
![Integration](https://user-images.githubusercontent.com/11767049/100610986-94fb6800-334b-11eb-8cf4-bdcba51362a5.gif)

**Comment by niulinlnc** [comment]
@bobslee cnongood(at)gmail(dot)com

**Comment by bobslee** [comment]
@niulinlnc please fix a typo in the extra banner, the word `Powerful`(one "l").

**Comment by niulinlnc** [comment]
@bobslee fixed

**Comment by bobslee** [comment]
@niulinlnc I've to wishes for the App icon.
The first one....

Please could you connect the shadow/beam below the dragging field and arrow?
It will look more familiar with the other Odoo App icons. Thanks!

![image](https://user-images.githubusercontent.com/328803/101087096-0dfbf900-35b2-11eb-839b-dd492a2f933a.png)

**Comment by bobslee** [comment]
@niulinlnc Please could you design an App icon for the extra/additional modules?
Like we already have to distinguish the banners.

See below..
Of course the icon of the main Formio App is OK, but it should stand-out from the other modules.
Maybe **reverse the dark/light blue** for the other App icons? Like you did with the banner :)

![image](https://user-images.githubusercontent.com/328803/101087710-e22d4300-35b2-11eb-90fc-4457d746c49d.png)

**Comment by niulinlnc** [comment]
@bobslee 
![icon](https://user-images.githubusercontent.com/11767049/101105676-1f242480-3609-11eb-813e-cb26e4ec7a77.png)

**Comment by bobslee** [comment]
@niulinlnc please could you remove the border, shown in screenshot.

![image](https://user-images.githubusercontent.com/328803/101157298-30c9f400-362a-11eb-9b0f-f25d9e9b3087.png)

**Comment by niulinlnc** [comment]
![icon](https://user-images.githubusercontent.com/11767049/101175112-bcba3b00-367f-11eb-9e55-403c53581686.png)

**Comment by niulinlnc** [comment]
@bobslee The border is caused by the bitmap embossing operation. In order to remove the border, I added drawing steps and improved drawing methods.

**Comment by bobslee** [comment]
@niulinlnc could you also address the extra icon? https://github.com/novacode-nl/odoo-formio/issues/86#issuecomment-738304583

In my PR #89 all modules seem to work on **version 14**
Would be great if you could complete this extra icon. So I can prepare (Odoo Apps Store too)
- Release version 14
- Replace icons and banner in versions 13, 12.

**Comment by niulinlnc** [comment]
@bobslee Please see which of the following two schemes is suitable:
![ex1](https://user-images.githubusercontent.com/11767049/101229694-7515cc80-36dc-11eb-848a-d654ddff6488.png)
![ext2](https://user-images.githubusercontent.com/11767049/101229698-7941ea00-36dc-11eb-82de-3c7b453c0fc7.png)

**Comment by bobslee** [comment]
@niulinlnc Thanks for your images. I know I ask a lot.. forgive me for that!

Would it be possible to use (somehow) equal blue-ish colorschemes, for the icons and banners?
3 blue colors would be ideal, but I see 4 different blue ones shown in screenshot.

![image](https://user-images.githubusercontent.com/328803/101238264-5a912280-36df-11eb-9dc7-31141db2eb30.png)

**Comment by bobslee** [comment]
@niulinlnc Any news?
I would like to publish the new icons and banners :)

(also v.14)

**Comment by bobslee** [comment]
@niulinlnc I just released the new design icons and banners. Also released version 14.

Check it out, looks awesome! Thanks, good work and very appreciated!

https://apps.odoo.com/apps/modules/browse?search=formio

**Comment by bobslee** [comment]
Hi @niulinlnc, see the screenshot below.
Unfortunately the description text looks somehow unsharp on the banners, with my resolution 1920x1080.
On mobile screen/resolution it looks neat!

Could you check please? Possible to improve somehow?
In case you've other improvements, just let me know :)

![image](https://user-images.githubusercontent.com/328803/101600959-54ab8200-39fc-11eb-9966-2230a98e1bff.png)

**Comment by bobslee** [comment]
@niulinlnc I really like both App **icons** (light and dark) !

Maybe you could just darken the dark blue in both banners... take the dark blue from the extra icon :)

**Comment by niulinlnc** [comment]
@bobslee I am busy with other things these days. Thank you for your update. A few questions about the picture, the answer is as follows:
1. When the small picture is displayed, it will be compressed automatically, so it is normal that the display is not clear. This can't be improved.
2. The dark blue is roughly consistent with the blue of the banner. It just looks different visually. Bitmap color change work more troublesome. It is recommended to improve it in the next major update.
