### ISSUE TITLE
Formio.js version updates in Windows environments are not available

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#90]
The formio.js version updates in Windows environments are not available, mainly:
1. The path cannot be found
2. The resource bundle cannot be uncompressed
Although in a formal environment it will run under Linux. However, in the Windows development environment, it is not easy to update the version.
![无标题](https://user-images.githubusercontent.com/11767049/100402594-9d2b7d00-3097-11eb-815e-90526ecbe177.jpg)

**Comment by niulinlnc** [comment]
@bobslee I've solved it. PR it later.

**Comment by niulinlnc** [comment]
@bobslee There is another problem here. If my odoo server is deployed under Docker environment, the module folder is generally read-only, and permissions will be involved when downloading the version here.
![无标题](https://user-images.githubusercontent.com/11767049/100496408-dabf0180-318e-11eb-94e1-693849b7d7d5.jpg)

**Comment by bobslee** [comment]
@niulinlnc Thanks for your PR. I shall review upcoming days.

Regarding the Docker issue...
Can't you add an extra Volume mount?
In case that's not ideal, which path do you suggest?

**Comment by bobslee** [comment]
@niulinlnc do you want to solve/improve this Docker / module directory issue first?
Or shall I merge your PR?

**Comment by bobslee** [comment]
@niulinlnc no need to discuss about the Docker setup issue?
I'm curious if and how you solved.
