### ISSUE TITLE
Some questions about translation

### ISSUE THREAD

**Issue by niulinlnc** [novacode-nl/odoo-formio#91]
Some questions about translation:
1. Now if there is only the default language (English), the language switch button will always be displayed on the form builder, it making the interface not simple enough.My desired result is that I can decide to display the language switch button or not to display the language switch button when designing the form.
2. Options ['language'] = language.replace('_', '-') this will cause option {'i18n': {'zh_CN': {'name2': '姓名'}, 'readOnly': True, 'language': 'zh-CN '} where the zh_CN shown in i180n is different from the zh-CN shown in language, so the default translation package will not take effect.

**Comment by niulinlnc** [comment]
About the second question, should all i18n[trans.lang_id.iso_code] be changed to i18n[trans.lang_id.iso_code.replace ('_', '-')]?

**Comment by bobslee** [comment]
@niulinlnc Indeed, I already had your experience with 1 useless language button.
Which appeared after my latest changes (last week).

Of course I would like to improve and solve this issue. I hope it can wait a few more days.

**Comment by bobslee** [comment]
@niulinlnc I think I solved this implementation. Shall push very soon (within hours).

**Comment by bobslee** [comment]
@niulinlnc  Please download and replace formio with version 8.1
Should be fixed now.
Let me know or close the issue :)

**Comment by bobslee** [comment]
@niulinlnc Please download and update to version 8.2 (formio).
I resolved and improved some issues with the language switcher (buttons) and also translations should work now.
I tested thoroughly, so I'm curious whether it works with you.
